# Curated resources for building software with AI and Python.
# Fields: (Level, Category, Title, Description, URL, Type, Cost)
# Descriptions are original paraphrases written for this catalogue.

B = "1 - Beginner"
I = "2 - Intermediate"
A = "3 - Advanced"
X = "All levels"

FREE = "Free"
FREEAPI = "Free tool + API usage costs"
FREEMIX = "Free, paid tier exists"
PAID = "Paid"

ROWS = [
    # ================================================= BEGINNER: Python core
    (B, "Python fundamentals", "The official Python tutorial",
     "The canonical language walkthrough. Note the caveat at the top: it targets people who have programmed before, so pair it with a true from-zero course if this is your first language.",
     "https://docs.python.org/3/tutorial/index.html", "Official docs", FREE),
    (B, "Python fundamentals", "Python.org - getting started",
     "Short official orientation page that points you at the tutorial, the library reference and the language reference in the right order.",
     "https://www.python.org/about/gettingstarted/", "Official docs", FREE),
    (B, "Python fundamentals", "Beginner's Guide (Python wiki)",
     "Community-maintained hub that splits advice by whether you have programmed before. The best single starting page if you are unsure where to begin.",
     "https://wiki.python.org/moin/BeginnersGuide", "Official wiki", FREE),
    (B, "Python fundamentals", "Beginner's Guide for non-programmers",
     "Curated tutorials that assume no prior programming experience at all - start here if 'variable' and 'loop' are new words.",
     "https://wiki.python.org/moin/BeginnersGuide/NonProgrammers", "Official wiki", FREE),
    (B, "Python fundamentals", "Python documentation home",
     "Bookmark this. The library reference is the single most useful page once you can write basic code.",
     "https://docs.python.org/3/", "Official docs", FREE),
    (B, "Python fundamentals", "All Python documentation",
     "Index of every official document: tutorial, library, language reference, HOWTOs and FAQs.",
     "https://www.python.org/doc/", "Official docs", FREE),
    (B, "Python fundamentals", "Automate the Boring Stuff with Python",
     "The best-known from-zero book, free to read online under a Creative Commons licence. Teaches programming through small practical automation scripts rather than toy exercises.",
     "https://automatetheboringstuff.com/", "Book (free online)", FREE),
    (B, "Python fundamentals", "Invent with Python - free books",
     "The author's other free books, including game-based and puzzle-based introductions.",
     "https://inventwithpython.com/", "Books (free online)", FREE),
    (B, "Python fundamentals", "freeCodeCamp: Scientific Computing with Python",
     "Free certification that now runs interactively in the browser: variables, loops, functions, then data structures and projects. No install needed to start.",
     "https://www.freecodecamp.org/learn/scientific-computing-with-python", "Course", FREE),
    (B, "Python fundamentals", "freeCodeCamp: Data Analysis with Python",
     "Follow-on certification covering reading data from CSV and SQL, then NumPy, pandas, Matplotlib and Seaborn.",
     "https://www.freecodecamp.org/learn/data-analysis-with-python", "Course", FREE),
    (B, "Python fundamentals", "freeCodeCamp: full beginner Python course",
     "Video-plus-projects course for absolute beginners, structured around small builds that reinforce each concept.",
     "https://www.freecodecamp.org/news/ultimate-beginners-python-course/", "Course", FREE),
    (B, "Python fundamentals", "Real Python - start here",
     "Well-edited tutorials with a clear beginner path. Free articles are plentiful; some video courses are paid.",
     "https://realpython.com/start-here/", "Tutorial site", FREEMIX),
    (B, "Python fundamentals", "Real Python - basics track",
     "Step-by-step fundamentals with hands-on examples and a skill quiz to place yourself.",
     "https://realpython.com/tutorials/basics/", "Tutorial site", FREEMIX),
    (B, "Python fundamentals", "Real Python - learning paths",
     "Ordered sequences (basics, web dev, data science) so you are not choosing tutorials at random.",
     "https://realpython.com/learning-paths/", "Tutorial site", FREEMIX),
    (B, "Python fundamentals", "Exercism - Python track",
     "Around 17 concepts and 146 exercises with automated tests and human mentoring. The fastest way to build fluency after a first course.",
     "https://exercism.org/tracks/python", "Practice", FREE),
    (B, "Python fundamentals", "Kaggle Learn",
     "Short, notebook-based micro-courses (Python, pandas, intro to ML) that run in the browser with certificates at no cost.",
     "https://www.kaggle.com/learn", "Course", FREE),
    (B, "Python fundamentals", "IBM: beginner's guide to Python",
     "Compact vendor-neutral primer written for people who have never coded, with the AI/automation context spelled out.",
     "https://developer.ibm.com/tutorials/python-beginners-guide/", "Tutorial", FREE),

    # ================================================= BEGINNER: first AI app
    (B, "Your first AI app", "OpenAI developer quickstart",
     "Official shortest path: create a key, make your first call, then generate text, analyse images or build an agent.",
     "https://developers.openai.com/api/docs/quickstart", "Official docs", FREEAPI),
    (B, "Your first AI app", "OpenAI SDKs and CLI overview",
     "Which official library or tool to use for application code, shell workflows or agent orchestration.",
     "https://developers.openai.com/api/docs/libraries", "Official docs", FREEAPI),
    (B, "Your first AI app", "Get started with Claude",
     "Anthropic's quickstart: export ANTHROPIC_API_KEY, create a venv, install the SDK, send your first message. Copy-paste ready.",
     "https://platform.claude.com/docs/en/get-started", "Official docs", FREEAPI),
    (B, "Your first AI app", "Anthropic Python SDK",
     "Sync and async usage, streaming, and the cloud variants (Bedrock, Vertex, Foundry) if you are already on a cloud.",
     "https://platform.claude.com/docs/en/cli-sdks-libraries/sdks/python", "Official docs", FREEAPI),
    (B, "Your first AI app", "Claude API usage primer",
     "Explains the single most misunderstood point for beginners: the Messages API is stateless, so you resend the whole conversation each turn.",
     "https://platform.claude.com/docs/en/claude_api_primer", "Official docs", FREEAPI),
    (B, "Your first AI app", "Working with the Messages API",
     "Multi-turn conversations, prefill techniques and vision input - the patterns you will reuse in every project.",
     "https://platform.claude.com/docs/en/build-with-claude/working-with-messages", "Official docs", FREEAPI),
    (B, "Your first AI app", "Build your first LLM application",
     "Demystifying article: an LLM call is one HTTP POST - you send messages, you get a message back, in about five lines.",
     "https://www.ml4devs.com/articles/llm-first-app-with-openai-api/", "Tutorial", FREEAPI),
    (B, "Your first AI app", "Your first OpenAI API project, step by step",
     "Guided first project with the reasoning explained at each step.",
     "https://machinelearningmastery.com/your-first-openai-api-project-in-python-step-by-step/", "Tutorial", FREEAPI),
    (B, "Your first AI app", "Build an AI chatbot with Python and the OpenAI API",
     "Goes beyond hello-world: conversation management, token budgeting to control cost, and personalities that persist across turns.",
     "https://www.dataquest.io/blog/build-an-ai-chatbot-with-python-and-the-openai-api/", "Tutorial", FREEAPI),
    (B, "Your first AI app", "OpenAI Python SDK developer guide",
     "Broad tour with runnable code: streaming, function calling, embeddings for search, vision, and error handling.",
     "https://www.askpython.com/python/examples/openai-python-sdk-developer-guide", "Tutorial", FREEAPI),
    (B, "Your first AI app", "Build a simple OpenAI app in Python",
     "A working chatbot in well under 50 lines - good for confirming your environment and key are set up correctly.",
     "https://www.aiplusinfo.com/blog/build-a-simple-openai-app-in-python/", "Tutorial", FREEAPI),
    (B, "Your first AI app", "How to build your first AI project",
     "Project-framing article aimed at producing something portfolio-worthy rather than a throwaway script.",
     "https://itsourcecode.com/blogs/first-ai-project-python-2026/", "Tutorial", FREEAPI),

    # ================================================= BEGINNER: give it a UI
    (B, "Give it a user interface", "Streamlit: build a basic LLM chat app",
     "Official tutorial for chat elements plus session state - a real chat UI in pure Python, no HTML or JavaScript.",
     "https://docs.streamlit.io/develop/tutorials/llms/build-conversational-apps", "Official docs", FREE),
    (B, "Give it a user interface", "Streamlit: LLM app quickstart",
     "Smallest end-to-end app that takes a prompt and returns generated text, with optional free cloud deployment.",
     "https://docs.streamlit.io/develop/tutorials/chat-and-llm-apps/llm-quickstart", "Official docs", FREE),
    (B, "Give it a user interface", "Turn a CLI chatbot into a web app",
     "Walkthrough of wrapping a script in Streamlit with settings controls, then deploying it publicly.",
     "https://www.dataquest.io/blog/build-a-web-interface-for-your-chatbot-with-streamlit/", "Tutorial", FREE),

    # ================================================= BEGINNER: run models locally
    (B, "Run models on your own machine", "Ollama quickstart",
     "Official quickstart for running open models locally on macOS, Windows or Linux - no API key, no per-token cost, prompts stay on your machine.",
     "https://docs.ollama.com/quickstart", "Official docs", FREE),
    (B, "Run models on your own machine", "Ollama with Python (Real Python)",
     "How to drive local models from Python, and why local removes both the subscription and the network dependency.",
     "https://realpython.com/ollama-python/", "Tutorial", FREE),
    (B, "Run models on your own machine", "Using Ollama to run LLMs locally",
     "Longer companion piece covering model management and practical hardware expectations.",
     "https://realpython.com/ollama/", "Tutorial", FREE),
    (B, "Run models on your own machine", "Ollama Python library tutorial",
     "Task-focused walkthrough of the official Python client with clean examples.",
     "https://www.datacamp.com/tutorial/ollama-python", "Tutorial", FREE),

    # ================================================= BEGINNER: prompting + ML concepts
    (B, "Prompting and AI concepts", "Google: what is prompt engineering",
     "Plain-language explanation of prompt design - context, instructions and examples - before you reach for frameworks.",
     "https://cloud.google.com/discover/what-is-prompt-engineering", "Vendor guide", FREE),
    (B, "Prompting and AI concepts", "Google Machine Learning Crash Course",
     "Animated explanations, visualisations and exercises. The fastest way to stop treating ML as magic.",
     "https://developers.google.com/machine-learning/crash-course", "Course", FREE),
    (B, "Prompting and AI concepts", "Prompt Engineering Guide (DAIR.AI)",
     "The most complete open guide to prompting techniques, with papers and examples. Useful at every level.",
     "https://github.com/dair-ai/Prompt-Engineering-Guide", "Open guide", FREE),
    (B, "Prompting and AI concepts", "Vertex AI: introduction to prompt design",
     "Vendor-neutral enough to be generally useful: structure, iteration and how to assess responses.",
     "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/introduction-prompt-design", "Official docs", FREE),

    # ================================================= INTERMEDIATE: real APIs
    (I, "Build a real API", "FastAPI tutorial",
     "The reference learning path for Python APIs. Each section builds on the last, and you can jump straight to the part you need.",
     "https://fastapi.tiangolo.com/tutorial/", "Official docs", FREE),
    (I, "Build a real API", "FastAPI: query parameters and validation",
     "How to declare validation and metadata on inputs so bad requests fail before they reach your logic.",
     "https://fastapi.tiangolo.com/tutorial/query-params-str-validations/", "Official docs", FREE),
    (I, "Build a real API", "FastAPI: fields inside Pydantic models",
     "Adding constraints and documentation inside request models rather than scattering checks through handlers.",
     "https://fastapi.tiangolo.com/tutorial/body-fields/", "Official docs", FREE),
    (I, "Build a real API", "Pydantic: get started",
     "Data validation that the whole AI ecosystem depends on - FastAPI, LangChain, Hugging Face and the OpenAI SDK all use it.",
     "https://pydantic.dev/docs/validation/latest/get-started/", "Official docs", FREE),
    (I, "Build a real API", "Pydantic: models concept guide",
     "The key mental model: Pydantic guarantees the types and constraints of the output, not of your input data.",
     "https://pydantic.dev/docs/validation/latest/concepts/models/", "Official docs", FREE),

    # ================================================= INTERMEDIATE: tooling
    (I, "Project setup & tooling", "uv - Python package and project manager",
     "Fast Rust-based replacement for pip/venv/pip-tools workflows. Manages Python versions, dependencies and lockfiles in one tool.",
     "https://docs.astral.sh/uv/", "Official docs", FREE),
    (I, "Project setup & tooling", "uv installation",
     "Install instructions per platform, including what happens when no prebuilt wheel exists.",
     "https://docs.astral.sh/uv/getting-started/installation/", "Official docs", FREE),
    (I, "Project setup & tooling", "uv feature overview",
     "What uv actually covers: installing Python itself, scripts, projects, tools and multi-version support.",
     "https://docs.astral.sh/uv/getting-started/features/", "Official docs", FREE),
    (I, "Project setup & tooling", "uvx - run tools without installing them",
     "Run a CLI tool in a throwaway environment. Note the gotcha that package and command names sometimes differ.",
     "https://docs.astral.sh/uv/guides/tools/", "Official docs", FREE),
    (I, "Project setup & tooling", "Ruff - linter and formatter",
     "Replaces Flake8 plus dozens of plugins, Black, isort, pydocstyle, pyupgrade and autoflake, and runs orders of magnitude faster.",
     "https://docs.astral.sh/ruff/", "Official docs", FREE),
    (I, "Project setup & tooling", "Ruff tutorial",
     "Adding the linter and formatter to an existing project without a large diff on day one.",
     "https://docs.astral.sh/ruff/tutorial/", "Official docs", FREE),
    (I, "Project setup & tooling", "pytest documentation",
     "Small readable tests that scale to full functional suites. The de facto standard for Python testing.",
     "https://docs.pytest.org/en/stable/", "Official docs", FREE),
    (I, "Project setup & tooling", "mypy documentation",
     "Static type checking. Type hints behave like comments at runtime, so you can adopt them gradually.",
     "https://mypy.readthedocs.io/en/stable/", "Official docs", FREE),
    (I, "Project setup & tooling", "mypy: getting started",
     "Important default to know: mypy skips unannotated functions, so early runs can look deceptively clean.",
     "https://mypy.readthedocs.io/en/stable/getting_started.html", "Official docs", FREE),
    (I, "Project setup & tooling", "mypy: inference and annotations",
     "When mypy can infer a type and when you must write it down.",
     "https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html", "Official docs", FREE),
    (I, "Project setup & tooling", "Python Packaging User Guide",
     "The authoritative source on packaging. Read this before following any blog post about setup.py.",
     "https://packaging.python.org/", "Official docs", FREE),
    (I, "Project setup & tooling", "Tutorial: packaging a Python project",
     "End-to-end: project structure, metadata, building a distribution and uploading to PyPI.",
     "https://packaging.python.org/en/latest/tutorials/packaging-projects/", "Official docs", FREE),
    (I, "Project setup & tooling", "Publishing to PyPI from GitHub Actions",
     "Uses PyPI trusted publishing, so you do not store long-lived API tokens in your repository.",
     "https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/", "Official docs", FREE),
    (I, "Project setup & tooling", "How to publish an open-source package to PyPI",
     "Friendlier narrative version of the packaging flow, with a quiz to check understanding.",
     "https://realpython.com/pypi-publish-python-package/", "Tutorial", FREEMIX),
    (I, "Project setup & tooling", "pyOpenSci: publish to PyPI",
     "Scientific-Python community guide, strong on build backends and reproducibility.",
     "https://www.pyopensci.org/python-package-guide/tutorials/publish-pypi.html", "Open guide", FREE),

    # ================================================= INTERMEDIATE: data & ML
    (I, "Data & classical ML", "scikit-learn: getting started",
     "Supervised and unsupervised learning, preprocessing, model selection and evaluation - the workhorse ML library.",
     "https://scikit-learn.org/stable/getting_started.html", "Official docs", FREE),
    (I, "Data & classical ML", "scikit-learn user guide",
     "Deep reference organised by technique. Reach for classical ML before an LLM when the task is prediction on tabular data.",
     "https://scikit-learn.org/stable/user_guide.html", "Official docs", FREE),
    (I, "Data & classical ML", "pandas user guide",
     "Topic-by-topic coverage of the data manipulation library that sits under most Python data work.",
     "https://pandas.pydata.org/docs/user_guide/", "Official docs", FREE),
    (I, "Data & classical ML", "NumPy: the absolute basics for beginners",
     "Arrays and vectorised operations - the foundation under pandas, scikit-learn, PyTorch and every embedding you will handle.",
     "https://numpy.org/doc/stable/user/absolute_beginners.html", "Official docs", FREE),
    (I, "Data & classical ML", "Combining pandas, NumPy and scikit-learn",
     "How the three libraries fit together in one pipeline instead of being learned in isolation.",
     "https://machinelearningmastery.com/how-to-combine-pandas-numpy-and-scikit-learn-seamlessly/", "Tutorial", FREE),
    (I, "Data & classical ML", "PyTorch tutorials",
     "Official tutorial hub: load data, build networks, train and save models.",
     "https://pytorch.org/tutorials/", "Official docs", FREE),
    (I, "Data & classical ML", "PyTorch quickstart",
     "One pass through a complete ML workflow, with links to go deeper on each stage.",
     "https://docs.pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html", "Official docs", FREE),
    (I, "Data & classical ML", "PyTorch: a 60 minute blitz",
     "Tensors, autograd, networks and an image classifier - the classic fast introduction.",
     "https://pytorch.org/tutorials/beginner/blitz/", "Official docs", FREE),
    (I, "Data & classical ML", "Zero to Mastery: Learn PyTorch",
     "Large free online book with code-along notebooks; good if the official tutorials feel too terse.",
     "https://www.learnpytorch.io/", "Book (free online)", FREE),
    (I, "Data & classical ML", "Hugging Face LLM course - introduction",
     "Free, ad-free course on transformers, datasets, tokenizers and the Hub. The best structured route into modern NLP.",
     "https://huggingface.co/learn/llm-course/en/chapter1/1", "Course", FREE),
    (I, "Data & classical ML", "HF course - environment setup",
     "Chapter 0: get a working environment before the concepts start.",
     "https://huggingface.co/learn/llm-course/en/chapter0/1", "Course", FREE),
    (I, "Data & classical ML", "HF course - what transformers can do",
     "Introduces the pipeline() helper: useful results in three lines before any theory.",
     "https://huggingface.co/learn/llm-course/en/chapter1/3", "Course", FREE),
    (I, "Data & classical ML", "HF course - how transformers work",
     "Attention and encoder-decoder architecture explained at the level a developer actually needs.",
     "https://huggingface.co/learn/llm-course/en/chapter1/4", "Course", FREE),
    (I, "Data & classical ML", "HF course - using transformers",
     "Chapter 2: models, tokenizers and the deliberate design choice that each model keeps its own layers.",
     "https://huggingface.co/learn/llm-course/en/chapter2/1", "Course", FREE),
    (I, "Data & classical ML", "HF course - a full training loop",
     "Writing the training loop yourself, which is where the abstractions finally make sense.",
     "https://huggingface.co/learn/llm-course/en/chapter3/4", "Course", FREE),

    # ================================================= INTERMEDIATE: reliable LLM output
    (I, "Getting reliable output", "OpenAI: structured outputs",
     "Force responses to match a JSON Schema. In Python you define the schema as a Pydantic model - this is the single biggest reliability win for LLM features.",
     "https://developers.openai.com/api/docs/guides/structured-outputs", "Official docs", FREEAPI),
    (I, "Getting reliable output", "OpenAI: function / tool calling",
     "How to let a model call your code and reach data outside its training set.",
     "https://developers.openai.com/api/docs/guides/function-calling", "Official docs", FREEAPI),
    (I, "Getting reliable output", "Cookbook: introduction to structured outputs",
     "Runnable notebook version with the schema-guarantee behaviour demonstrated.",
     "https://developers.openai.com/cookbook/examples/structured_outputs_intro", "Official cookbook", FREEAPI),
    (I, "Getting reliable output", "openai-python helpers",
     "SDK helpers, including parsing straight into Pydantic models and the pydantic_function_tool shortcut.",
     "https://github.com/openai/openai-python/blob/main/helpers.md", "Official repo", FREEAPI),
    (I, "Getting reliable output", "Pydantic AI: outputs",
     "Framework built by the Pydantic team where typed output is the default rather than an add-on.",
     "https://pydantic.dev/docs/ai/core-concepts/output/", "Official docs", FREEAPI),

    # ================================================= INTERMEDIATE: RAG
    (I, "RAG & semantic search", "LlamaIndex: what RAG is",
     "Clearest short explanation of the loop: index your data, retrieve the relevant context, send it with the prompt.",
     "https://developers.llamaindex.ai/python/framework/understanding/rag/", "Official docs", FREEAPI),
    (I, "RAG & semantic search", "LlamaIndex starter tutorial",
     "Smallest working RAG app, with notes on pointing it at any OpenAI-compatible endpoint.",
     "https://developers.llamaindex.ai/python/framework/getting_started/starter_example/", "Official docs", FREEAPI),
    (I, "RAG & semantic search", "Building RAG from scratch",
     "Same pipeline using only low-level pieces - LLM, prompt, embedding model - so you understand what the framework hides.",
     "https://developers.llamaindex.ai/python/framework/optimizing/building_rag_from_scratch/", "Official docs", FREEAPI),
    (I, "RAG & semantic search", "RAG from scratch, open-source only",
     "Ingestion into a vector database and retrieval back out, with no proprietary services involved.",
     "https://developers.llamaindex.ai/python/examples/low_level/oss_ingestion_retrieval/", "Official docs", FREE),
    (I, "RAG & semantic search", "LangChain: learn hub",
     "Entry point to LangChain's tutorials and conceptual guides for Python.",
     "https://docs.langchain.com/oss/python/learn", "Official docs", FREEAPI),
    (I, "RAG & semantic search", "LangChain: RAG with deep agents",
     "End-to-end documentation Q&A agent that offloads retrieved chunks to the filesystem to keep the orchestrator's context clean.",
     "https://docs.langchain.com/oss/python/deepagents/rag", "Official docs", FREEAPI),
    (I, "RAG & semantic search", "Sentence Transformers (SBERT)",
     "The standard library for embeddings and rerankers, and for training your own. Underpins most local retrieval stacks.",
     "https://sbert.net/", "Official docs", FREE),
    (I, "RAG & semantic search", "Sentence Transformers usage guide",
     "Computing embeddings in practice, including checking which modalities a model supports.",
     "https://sbert.net/docs/sentence_transformer/usage/usage.html", "Official docs", FREE),
    (I, "RAG & semantic search", "Sentence Transformers on the HF Hub",
     "How embeddings place similar text close together, enabling semantic search, clustering and retrieval.",
     "https://huggingface.co/docs/hub/sentence-transformers", "Official docs", FREE),
    (I, "RAG & semantic search", "Sentence Transformers complete guide",
     "Practical progression: first embeddings, sparse search, cross-encoder reranking, ONNX speedups, then fine-tuning.",
     "https://dataaspirant.com/blog/sentence-transformers/", "Tutorial", FREE),
    (I, "RAG & semantic search", "Qdrant documentation",
     "Vector database docs with genuinely good conceptual material on similarity search.",
     "https://qdrant.tech/documentation/", "Official docs", FREEMIX),
    (I, "RAG & semantic search", "Qdrant: hybrid search with LlamaIndex",
     "Combining dense and keyword retrieval over PDFs - the upgrade that fixes most 'RAG cannot find it' complaints.",
     "https://qdrant.tech/documentation/examples/hybrid-search-llamaindex-jinaai/", "Official docs", FREEMIX),
    (I, "RAG & semantic search", "Qdrant: multimodal and multilingual RAG",
     "Retrieval across text and images by choosing an embedding model that bridges both.",
     "https://qdrant.tech/documentation/multimodal-search/", "Official docs", FREEMIX),
    (I, "RAG & semantic search", "FAISS + Ollama local RAG walkthrough",
     "Fully local retrieve-read-generate pipeline with HNSW indexing, grounded answers and sentence-level support scoring.",
     "https://pyimagesearch.com/2026/02/23/vector-search-using-ollama-for-retrieval-augmented-generation-rag/", "Tutorial", FREE),
    (I, "RAG & semantic search", "RAG with ChromaDB and Ollama for beginners",
     "Gentle version of the same stack using SentenceTransformers embeddings.",
     "https://medium.com/@arunpatidar26/rag-chromadb-ollama-python-guide-for-beginners-30857499d0a0", "Tutorial", FREE),
    (I, "RAG & semantic search", "Vector databases compared",
     "Qdrant, Weaviate, Milvus and Chroma set up with Docker and exercised with real indexing and query code.",
     "https://devtoolsguide.hashnode.dev/vector-databases-for-rag-qdrant-weaviate-and-milvus-compared", "Community blog", FREE),

    # ================================================= INTERMEDIATE: ship it
    (I, "Ship and deploy", "Hugging Face Docker Spaces",
     "Deploy any containerised Python app - FastAPI included - on free hosting. Note the default exposed port is 7860.",
     "https://huggingface.co/docs/hub/en/spaces-sdks-docker", "Official docs", FREEMIX),
    (I, "Ship and deploy", "Hugging Face Streamlit Spaces",
     "The lowest-friction way to put a Python AI demo on the public internet.",
     "https://huggingface.co/docs/hub/en/spaces-sdks-streamlit", "Official docs", FREEMIX),
    (I, "Ship and deploy", "Deploy FastAPI on Spaces via Docker",
     "Community write-up including the free-tier limitations that bite people mid-project.",
     "https://huggingface.co/blog/HemanthSai7/deploy-applications-on-huggingface-spaces", "Community blog", FREEMIX),
    (I, "Ship and deploy", "Hugging Face: deploy your own container",
     "Inference Endpoints with a custom image; note the model is mounted at /repository, not fetched from the Hub.",
     "https://huggingface.co/docs/inference-endpoints/en/engines/custom_container", "Official docs", PAID),
    (I, "Ship and deploy", "Serving Hugging Face models with Docker",
     "Production packaging notes, including the CUDA base-image mismatch that fails silently as 'GPU not visible'.",
     "https://markaicode.com/integrate/hugging-face-with-docker/", "Community blog", FREE),

    # ================================================= ADVANCED: agents
    (A, "Agents & orchestration", "Anthropic: building effective agents",
     "The most valuable article on this list. Argues for the simplest thing that works, and for treating agents as a latency/cost trade rather than a default.",
     "https://www.anthropic.com/engineering/building-effective-agents", "Engineering blog", FREE),
    (A, "Agents & orchestration", "Anthropic: effective context engineering",
     "Context engineering as the successor to prompt engineering - deciding what the model sees, not just how you phrase it.",
     "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents", "Engineering blog", FREE),
    (A, "Agents & orchestration", "Anthropic: writing tools for agents",
     "Tool design is where agent quality is won or lost, plus how to evaluate and iterate on tool definitions.",
     "https://www.anthropic.com/engineering/writing-tools-for-agents", "Engineering blog", FREE),
    (A, "Agents & orchestration", "Anthropic: code execution with MCP",
     "Why loading hundreds of tool definitions upfront slows agents and inflates cost, and what to do instead.",
     "https://www.anthropic.com/engineering/code-execution-with-mcp", "Engineering blog", FREE),
    (A, "Agents & orchestration", "Anthropic: harnesses for long-running agents",
     "Splitting work into an initializer agent and a coding agent that leaves artifacts for the next session - the practical answer to finite context.",
     "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents", "Engineering blog", FREE),
    (A, "Agents & orchestration", "Anthropic: harness design for long-running apps",
     "Follow-up experiment decomposing a spec into tasks and carrying context across sessions.",
     "https://www.anthropic.com/engineering/harness-design-long-running-apps", "Engineering blog", FREE),
    (A, "Agents & orchestration", "OpenAI Agents SDK quickstart",
     "Define an agent with instructions and a name, run it, then add tools and specialist agents as the workflow grows.",
     "https://openai.github.io/openai-agents-python/quickstart/", "Official docs", FREEAPI),
    (A, "Agents & orchestration", "OpenAI Agents SDK repository",
     "Lightweight multi-agent framework that is provider-agnostic - it works with many non-OpenAI models too.",
     "https://github.com/openai/openai-agents-python/blob/main/README.md", "Official repo", FREEAPI),
    (A, "Agents & orchestration", "Agents SDK: MCP integration and safety",
     "Read the security guidance: connect only to servers you trust, use least-privilege credentials, keep tokens out of URLs.",
     "https://github.com/openai/openai-agents-python/blob/main/docs/mcp.md", "Official repo", FREEAPI),
    (A, "Agents & orchestration", "OpenAI agents quickstart (API docs)",
     "The docs-site version of the same path, kept in step with API changes.",
     "https://developers.openai.com/api/docs/guides/agents/quickstart", "Official docs", FREEAPI),
    (A, "Agents & orchestration", "LangGraph overview",
     "Low-level orchestration: mix deterministic hand-written steps with LLM-driven steps in one graph.",
     "https://docs.langchain.com/oss/python/langgraph/overview", "Official docs", FREEAPI),
    (A, "Agents & orchestration", "LangGraph: Graph API vs Functional API",
     "Choosing between the two styles, which share a runtime and can be mixed in one application.",
     "https://docs.langchain.com/oss/python/langgraph/choosing-apis", "Official docs", FREEAPI),
    (A, "Agents & orchestration", "LangGraph: build a SQL agent",
     "Substantial worked example - an agent answering questions against a real database.",
     "https://docs.langchain.com/oss/python/langgraph/sql-agent", "Official docs", FREEAPI),
    (A, "Agents & orchestration", "LangGraph Python reference",
     "API reference for durable execution, streaming, human-in-the-loop, persistence and memory.",
     "https://reference.langchain.com/python/langgraph", "Official docs", FREEAPI),
    (A, "Agents & orchestration", "Kaggle/Google: Agents whitepaper",
     "Foundational write-up on agents as reasoning plus tools plus external information.",
     "https://www.kaggle.com/whitepaper-agents", "Whitepaper", FREE),
    (A, "Agents & orchestration", "Kaggle/Google: Agents Companion",
     "Follow-up covering evaluation and operational concerns for agents in production.",
     "https://www.kaggle.com/whitepaper-agent-companion", "Whitepaper", FREE),
    (A, "Agents & orchestration", "A developer's guide to production-ready agents",
     "Google Cloud's take on moving from a demo agent to one you can operate.",
     "https://cloud.google.com/blog/products/ai-machine-learning/a-devs-guide-to-production-ready-ai-agents", "Vendor blog", FREE),
    (A, "Agents & orchestration", "Google ADK crash course (codelab)",
     "Hands-on lab building tool-using, planning agents with the Agent Development Kit.",
     "https://codelabs.developers.google.com/onramp/instructions", "Codelab", FREE),

    # ================================================= ADVANCED: MCP
    (A, "MCP - extend your tools", "MCP: build a server",
     "Official tutorial. Critical detail for STDIO servers: never write to stdout - a stray print() corrupts the protocol.",
     "https://modelcontextprotocol.io/docs/develop/build-server", "Official docs", FREE),
    (A, "MCP - extend your tools", "MCP Python SDK",
     "SDK docs for exposing your data and functions to any MCP-capable AI client.",
     "https://py.sdk.modelcontextprotocol.io/", "Official docs", FREE),
    (A, "MCP - extend your tools", "MCP Python SDK: get started",
     "From nothing to a tested server: install, build, connect to a real host, test with an in-memory client.",
     "https://py.sdk.modelcontextprotocol.io/v2/get-started/", "Official docs", FREE),
    (A, "MCP - extend your tools", "MCP Python SDK repository",
     "Source and examples. Think of an MCP server as a web API shaped for LLM interaction.",
     "https://github.com/modelcontextprotocol/python-sdk", "Official repo", FREE),

    # ================================================= ADVANCED: fine-tuning
    (A, "Fine-tuning & training", "PEFT: LoRA concept guide",
     "Low-Rank Adaptation explained: decompose a large matrix into two small ones and train far fewer parameters.",
     "https://huggingface.co/docs/peft/main/en/conceptual_guides/lora", "Official docs", FREE),
    (A, "Fine-tuning & training", "PEFT: adapters overview",
     "How adapter methods compare, and merging adapter weights back into the base model to remove inference latency.",
     "https://huggingface.co/docs/peft/main/en/conceptual_guides/adapter", "Official docs", FREE),
    (A, "Fine-tuning & training", "HF course: LoRA chapter",
     "Course treatment of LoRA, typically cutting trainable parameters by around 90 percent.",
     "https://huggingface.co/learn/llm-course/en/chapter11/4", "Course", FREE),
    (A, "Fine-tuning & training", "TRL: Unsloth integration",
     "Framework claiming roughly 2x faster training with far less VRAM - the practical route on a single GPU.",
     "https://huggingface.co/docs/trl/main/unsloth_integration", "Official docs", FREE),
    (A, "Fine-tuning & training", "HF course: GRPO with Unsloth",
     "Reinforcement-style post-training on modest hardware.",
     "https://huggingface.co/learn/llm-course/en/chapter12/6", "Course", FREE),
    (A, "Fine-tuning & training", "Fine-tuning your first LLM, end to end",
     "Deliberately recipe-shaped tutorial: fine-tune a small model first, understand the theory afterwards.",
     "https://huggingface.co/blog/dvgodoy/fine-tuning-llm-hugging-face", "Tutorial", FREE),

    # ================================================= ADVANCED: serving
    (A, "Serving & scaling", "vLLM quickstart",
     "High-throughput inference server with an OpenAI-compatible API. Installation via uv, including Apple Silicon notes.",
     "https://docs.vllm.ai/en/stable/getting_started/quickstart/", "Official docs", FREE),
    (A, "Serving & scaling", "Ray Serve LLM",
     "Distributed, multi-node model serving that also exposes an OpenAI-compatible API.",
     "https://docs.ray.io/en/latest/serve/llm/index.html", "Official docs", FREE),
    (A, "Serving & scaling", "Ray Serve LLM quickstart",
     "Runnable examples sized for a single mid-range GPU before you scale out.",
     "https://docs.ray.io/en/latest/serve/llm/quick-start.html", "Official docs", FREE),
    (A, "Serving & scaling", "Ray Data: batch inference with LLMs",
     "Scalable offline/batch inference over datasets, driving vLLM or SGLang directly or calling hosted endpoints.",
     "https://docs.ray.io/en/master/data/working-with-llms.html", "Official docs", FREE),
    (A, "Serving & scaling", "vLLM multi-node serving with Ray",
     "Helper script and guidance for spanning GPUs across machines.",
     "https://docs.vllm.ai/en/latest/examples/ray_serving/multi-node-serving/", "Official docs", FREE),

    # ================================================= ADVANCED: evals
    (A, "Evaluation & testing of AI", "Ragas: evaluate an LLM application",
     "Minimal-prerequisite workflow for measuring an LLM app instead of eyeballing outputs.",
     "https://docs.ragas.io/en/stable/getstarted/evals/", "Official docs", FREEAPI),
    (A, "Evaluation & testing of AI", "DeepEval: getting started",
     "Test-case model (input, actual output, optional expected output) that turns evaluation into unit testing.",
     "https://deepeval.com/docs/getting-started", "Official docs", FREEAPI),
    (A, "Evaluation & testing of AI", "DeepEval for RAG",
     "Plugs into pytest so a failing quality metric fails the build, locally and in CI.",
     "https://deepeval.com/docs/getting-started-rag", "Official docs", FREEAPI),
    (A, "Evaluation & testing of AI", "promptfoo: introduction",
     "Local-first open-source CLI for evaluating and red-teaming LLM apps.",
     "https://www.promptfoo.dev/docs/intro/", "Official docs", FREE),
    (A, "Evaluation & testing of AI", "promptfoo: getting started",
     "Build a working eval that compares prompts across models and opens a side-by-side web view.",
     "https://www.promptfoo.dev/docs/getting-started/", "Official docs", FREE),
    (A, "Evaluation & testing of AI", "promptfoo: evaluating RAG pipelines",
     "How to score retrieval and generation separately, so you know which half is broken.",
     "https://www.promptfoo.dev/docs/guides/evaluate-rag/", "Official docs", FREE),
    (A, "Evaluation & testing of AI", "promptfoo hands-on tutorial",
     "Framing that makes evals click: a test suite for your prompts rather than your code.",
     "https://www.datacamp.com/tutorial/promptfoo-tutorial", "Tutorial", FREE),

    # ================================================= ADVANCED: observability
    (A, "Observability & MLOps", "MLflow Tracing",
     "OpenTelemetry-compatible tracing that captures inputs, outputs and metadata at every intermediate step of a request.",
     "https://mlflow.org/docs/latest/tracing/", "Official docs", FREE),
    (A, "Observability & MLOps", "MLflow for agents and LLMs",
     "The GenAI half of MLflow: tracing, evaluation and prompt management without vendor lock-in.",
     "https://mlflow.org/docs/latest/genai/index.html", "Official docs", FREE),
    (A, "Observability & MLOps", "MLflow: OpenTelemetry integration",
     "Ingesting and exporting traces in GenAI semantic-convention format so your tooling stays swappable.",
     "https://mlflow.org/docs/latest/genai/tracing/opentelemetry/", "Official docs", FREE),
    (A, "Observability & MLOps", "OpenTelemetry GenAI semantic conventions",
     "The CNCF-backed standard schema for AI telemetry, adopted across major clouds and observability vendors.",
     "https://www.mlflow.org/docs/latest/genai/tracing/opentelemetry/genai-semconv/", "Official docs", FREE),
    (A, "Observability & MLOps", "Langfuse via OpenTelemetry",
     "Langfuse as an OTel backend, so instrumentation is not tied to one vendor's SDK.",
     "https://langfuse.com/integrations/other/mlflow", "Official docs", FREEMIX),

    # ================================================= ADVANCED: security
    (A, "Security", "OWASP Top 10 for LLM Applications",
     "The reference list of critical LLM application vulnerabilities. Treat it as your pre-launch checklist.",
     "https://owasp.org/www-project-top-10-for-large-language-model-applications/", "Standard", FREE),
    (A, "Security", "OWASP LLM Top 10 repository",
     "Community-developed source material for developers, architects and security practitioners.",
     "https://github.com/GenAI-Security-Project/GenAI-LLM-Top10", "Standard", FREE),
    (A, "Security", "What changed in the 2026 LLM Top 10, and how to test it",
     "Category-by-category testing guidance, built against real incident data.",
     "https://www.giskard.ai/knowledge/owasp-top-10-for-llm-2026", "Vendor blog", FREE),
    (A, "Security", "News analysis: prompt injection remains number one",
     "Independent coverage of the 2026 edition and the 'defense effect' that makes the risk look smaller than it is.",
     "https://www.helpnetsecurity.com/2026/08/06/owasp-2026-llm-top-10-released/", "News", FREE),
    (A, "Security", "From model risks to agentic security",
     "Why Excessive Agency climbed the list - directly relevant if you give an agent tools that can act.",
     "https://www.akamai.com/blog/ai/owasp-top-10-llm-applications-2026-realistic-security-model", "Vendor blog", FREE),

    # ================================================= ADVANCED: performance & architecture
    (A, "Concurrency & performance", "asyncio: coroutines and tasks",
     "Running many LLM or HTTP calls concurrently instead of serially - usually the largest latency win in an AI app.",
     "https://docs.python.org/3/library/asyncio-task.html", "Official docs", FREE),
    (A, "Concurrency & performance", "A conceptual overview of asyncio",
     "Official HOWTO that finally makes the event loop intuitive.",
     "https://docs.python.org/3/howto/a-conceptual-overview-of-asyncio.html", "Official docs", FREE),
    (A, "Concurrency & performance", "Developing with asyncio",
     "Debugging guidance and the trap that one blocking call stalls every other task in the thread.",
     "https://docs.python.org/3/library/asyncio-dev.html", "Official docs", FREE),
    (A, "Concurrency & performance", "Python support for free threading",
     "The no-GIL execution mode: what it enables and why only threading-aware programs get faster.",
     "https://docs.python.org/3/howto/free-threading-python.html", "Official docs", FREE),
    (A, "Concurrency & performance", "asyncio and free-threaded Python",
     "How the two concurrency stories interact in current Python.",
     "https://docs.python.org/3/library/asyncio-threading.html", "Official docs", FREE),
    (A, "Concurrency & performance", "What's new in Python 3.14",
     "Template string literals, deferred annotation evaluation and subinterpreter support in the standard library.",
     "https://docs.python.org/3/whatsnew/3.14.html", "Official docs", FREE),
    (A, "Concurrency & performance", "Scaling asyncio on free-threaded Python",
     "Deep engineering write-up with benchmarks, for when you are optimising a real I/O-heavy service.",
     "https://labs.quansight.org/blog/scaling-asyncio-on-free-threaded-python", "Engineering blog", FREE),
    (A, "Architecture & code quality", "Architecture Patterns with Python (free online)",
     "Repository, Unit of Work, service layer and event-driven patterns in Python. The book to read when your AI app outgrows one file.",
     "https://www.cosmicpython.com/", "Book (free online)", FREE),
    (A, "Architecture & code quality", "Cosmic Python: preface",
     "Why the authors wrote it - the material they teach every new team member.",
     "https://cosmicpython.com/book/preface", "Book (free online)", FREE),
    (A, "Architecture & code quality", "Cosmic Python: domain modelling",
     "Behaviour first, storage second - the habit that keeps business logic out of your handlers and prompts.",
     "https://cosmicpython.com/book/part1", "Book (free online)", FREE),

    # ================================================= ADVANCED: cost
    (A, "Cost control", "Prompt caching guide",
     "Cache the stable prefix of your prompts and pay a fraction for those tokens. Often the single cheapest optimisation available.",
     "https://devtoollab.com/blog/prompt-caching-guide", "Community blog", FREE),
    (A, "Cost control", "Prompt compression and cache tuning",
     "Four combinable techniques - compression, semantic caching, reasoning pruning and output limits - with measured savings.",
     "https://www.sitepoint.com/prompt-compression-cache-tuning-llm-api-costs/", "Tutorial", FREE),
    (A, "Cost control", "Claude API token optimisation",
     "Prompt engineering, exact-match caching with Redis and model routing, quantified.",
     "https://www.sitepoint.com/claude-api-token-optimization/", "Tutorial", FREE),
    (A, "Cost control", "Prompt caching and token efficiency in depth",
     "Cache breakpoints, batch processing and request structuring - two apps can get the same answer at very different cost.",
     "https://hidekazu-konishi.com/entry/anthropic_claude_api_prompt_caching_and_token_efficiency.html", "Engineering blog", FREE),
    (A, "Cost control", "Ten ways to reduce LLM inference cost",
     "Checklist with worked arithmetic on how prompt length dominates spend at volume.",
     "https://www.nops.io/blog/llm-cost-optimization-tips/", "Vendor blog", FREE),

    # ================================================= ALL LEVELS: AI-assisted development
    (X, "Let AI help you build", "Kiro documentation",
     "Spec-driven agentic IDE and CLI from AWS: turn a prompt into requirements, design and sequenced tasks. See the companion Kiro workbook for 292 more links.",
     "https://kiro.dev/docs/", "Official docs", FREEMIX),
    (X, "Let AI help you build", "Cursor documentation",
     "Agent, rules, MCP and CLI docs for the AI-first editor.",
     "https://cursor.com/docs", "Official docs", FREEMIX),
    (X, "Let AI help you build", "Awesome AI coding agents",
     "Community comparison of Claude Code, Aider, Cursor, Windsurf and others, explicitly without sponsored placements.",
     "https://github.com/BrethofAI/awesome-ai-coding-agents", "Community list", FREE),
    (X, "Let AI help you build", "Awesome CLI coding agents",
     "Terminal agents that can read, write and execute code in your repository, and how they differ from chat assistants.",
     "https://github.com/bradAGI/awesome-cli-coding-agents", "Community list", FREE),
    (X, "Let AI help you build", "Best AI coding assistants for Python",
     "Argues the backing models have converged, so the workflow shell is what you are actually choosing between.",
     "https://codegym.cc/groups/posts/best-ai-coding-assistants-python-2026", "Community blog", FREE),
    (X, "Let AI help you build", "The new rules of context engineering",
     "What changed for prompting and context with the newest model generation - applies whether you use an IDE agent or your own code.",
     "https://claude.com/blog/the-new-rules-of-context-engineering-for-claude-5-generation-models", "Vendor blog", FREE),
]


# ---------------------------------------------------------------------
# Staged roadmap: (Level, Stage, Goal, What to learn, Build this, Done when)
# ---------------------------------------------------------------------
ROADMAP = [
    (B, "B1", "Get Python running",
     "Install Python and an editor. Variables, types, conditionals, loops, functions, lists and dicts. How to read a traceback.",
     "A script that reads a text file, counts word frequencies and prints the top ten.",
     "You can write a 30-line script from scratch without copying, and you can fix your own errors."),
    (B, "B2", "Automate something boring",
     "File and folder handling, CSV, JSON, HTTP requests, virtual environments, installing packages.",
     "A script that pulls data from a public API and writes a tidy CSV report.",
     "You created a venv, installed a package and your script runs on a fresh machine."),
    (B, "B3", "Make your first AI call",
     "API keys as environment variables (never in code), the messages format, the fact that chat APIs are stateless, token cost basics.",
     "A command-line chatbot that keeps conversation history and has a system prompt you wrote.",
     "You understand why you resend history every turn, and you can estimate what a session costs."),
    (B, "B4", "Give it a face and run it locally",
     "Streamlit basics, session state, streaming responses. Ollama for local models.",
     "The same chatbot as a web app, with a model picker that can switch to a local Ollama model.",
     "A non-technical person can use your app, and it still works with no internet and no API key."),
    (I, "I1", "Write code you can maintain",
     "Modules and packages, type hints, pytest, Ruff, uv, pyproject.toml, logging instead of print, config via environment.",
     "Refactor your chatbot into a package with tests, a lockfile, linting and a pinned Python version.",
     "One command sets up the project, one runs the tests, and CI could run both."),
    (I, "I2", "Expose it as a real API",
     "FastAPI, Pydantic request/response models, dependency injection, error handling, async endpoints.",
     "A FastAPI service wrapping your AI feature, with validated inputs and a documented schema.",
     "Bad input returns a helpful 422 rather than a 500, and /docs describes your API accurately."),
    (I, "I3", "Make the model output trustworthy",
     "Structured outputs with a Pydantic schema, tool/function calling, retries and timeouts, graceful degradation.",
     "A feature that extracts structured records from messy text and never returns unparseable output.",
     "You parse responses into typed objects with no regex and no try/except around json.loads."),
    (I, "I4", "Ground answers in your own data",
     "Embeddings, chunking strategy, vector stores, retrieval, hybrid search, reranking, citation of sources.",
     "A RAG service over your own documents that answers with citations and says 'I don't know' when retrieval fails.",
     "You can explain why a given chunk was retrieved, and you have fixed at least one bad-retrieval case."),
    (I, "I5", "Ship it",
     "Docker, environment configuration, secrets handling, a deployment target, basic monitoring.",
     "The RAG service running in a container on a public URL.",
     "Someone else can hit your URL, and you can redeploy from a clean checkout."),
    (A, "A1", "Build agents deliberately",
     "When NOT to use an agent. Tool design, orchestration with LangGraph or the Agents SDK, sub-agents, human-in-the-loop, durable state.",
     "An agent that completes a multi-step task with tools, checkpoints between steps and an approval gate on destructive actions.",
     "You can name a task you deliberately solved with a plain prompt chain instead of an agent, and justify it."),
    (A, "A2", "Measure quality instead of guessing",
     "Eval datasets, LLM-as-judge and its limits, retrieval vs generation metrics, regression testing in CI.",
     "An eval suite that fails your build when answer quality or retrieval drops.",
     "A prompt change that looks fine by eye but scores worse is caught automatically."),
    (A, "A3", "Operate it",
     "Tracing with OpenTelemetry GenAI conventions, cost and latency dashboards, prompt caching, batching, model routing.",
     "Full tracing on your service plus caching that measurably cuts token spend.",
     "You can answer 'why was this response slow and what did it cost?' from traces alone."),
    (A, "A4", "Secure it",
     "OWASP LLM Top 10, prompt injection and indirect injection, least-privilege tools, output handling, secrets and data boundaries.",
     "A red-team script that attempts injection and privilege abuse against your own app, plus the fixes.",
     "An untrusted document cannot make your agent call a tool it should not, and you have a test proving it."),
    (A, "A5", "Go deeper where it pays",
     "Choose by need: fine-tuning with LoRA/QLoRA, self-hosted serving with vLLM or Ray, async and free-threaded performance work, architecture patterns.",
     "One substantial piece: a fine-tuned model that beats prompting on your task, or self-hosted serving at a lower cost per token.",
     "You have numbers - accuracy, latency or cost - showing the advanced approach beat the simple one."),
]
