# Data set of Kiro (AWS agentic IDE) resources.
# Fields: (Category, Title, Description, URL, Source type)
# Descriptions are original paraphrases written for this catalog.

ROWS = [
    # ---------------- 1. Official overview ----------------
    ("Official - Overview", "Kiro - official home page",
     "Product landing page. Explains the core pitch: prompts become requirements, designs and sequenced tasks, executed by parallel agents and checked with property-based tests.",
     "https://kiro.dev/", "Official site"),
    ("Official - Overview", "Kiro Docs - documentation home",
     "Entry point for all official documentation. Notes that one agent harness powers every surface (IDE, CLI, Web, Mobile) so specs, steering and config carry over.",
     "https://kiro.dev/docs/", "Official docs"),
    ("Official - Overview", "Kiro IDE product page",
     "Overview of the desktop IDE surface: spec planning, parallel agent execution, and verification tooling.",
     "https://kiro.dev/ide/", "Official site"),
    ("Official - Overview", "Kiro CLI product page",
     "Overview of the terminal surface: custom agents in an interactive TUI, workflow automation, work in large codebases.",
     "https://kiro.dev/cli/", "Official site"),
    ("Official - Overview", "Kiro Web product page",
     "Browser surface overview: Kiro plans, runs in a sandboxed environment and delivers a pull request for review.",
     "https://kiro.dev/web/", "Official site"),
    ("Official - Overview", "Kiro Mobile",
     "Mobile/iOS surface. Sessions, model preferences and connected repos sync across web and iOS; monitor several sessions and PR status in one view.",
     "https://kiro.dev/mobile/", "Official site"),
    ("Official - Overview", "Kiro FAQ",
     "Official answers to the most common questions: what Kiro is, how to sign in (GitHub, Google, AWS Builder ID, IAM Identity Center), specs vs vibe coding, account requirements.",
     "https://kiro.dev/faq/", "Official FAQ"),
    ("Official - Overview", "Downloads page",
     "Installers for macOS (Intel and Apple Silicon), Windows x64 and Linux (Debian/Ubuntu package or universal tarball), plus CLI install instructions.",
     "https://kiro.dev/downloads/", "Official site"),
    ("Official - Overview", "Kiro blog index",
     "All official announcements, deep dives and feature explainers in one place - useful when you need the reasoning behind a feature, not just the reference docs.",
     "https://kiro.dev/blog/", "Official blog"),
    ("Official - Overview", "Changelog (all releases)",
     "Running list of releases across IDE, CLI and Web with per-feature notes. First place to check whether a bug you hit was already fixed.",
     "https://kiro.dev/changelog/", "Official changelog"),
    ("Official - Overview", "AWS documentation overview for Kiro",
     "AWS-hosted documentation hub for Kiro. Describes how Kiro reads workspace structure and breaks a prompt into implementation steps you review and iterate on.",
     "https://aws.amazon.com/documentation-overview/kiro/", "AWS docs"),
    ("Official - Overview", "Blog: Introducing Kiro",
     "The original launch post. Good background on the design intent behind specs and event-driven agent hooks that run tasks in the background.",
     "https://kiro.dev/blog/introducing-kiro/", "Official blog"),
    ("Official - Overview", "Blog: Kiro is generally available",
     "GA announcement covering property-based testing for spec correctness, checkpointing, the new CLI, and centrally managed team plans.",
     "https://kiro.dev/blog/general-availability/", "Official blog"),
    ("Official - Overview", "Blog: Introducing Kiro Web",
     "Explains multi-repository sessions in the browser: pick repos, describe the change, and the agent coordinates edits and PRs across all of them.",
     "https://kiro.dev/blog/introducing-kiro-web/", "Official blog"),
    ("Official - Overview", "GitHub: kirodotdev/Kiro README",
     "Official repository README - concise summary of the IDE and CLI, spec-driven development, hooks and powers. The repo itself is where issues are filed.",
     "https://github.com/kirodotdev/Kiro/blob/main/README.md", "GitHub"),

    # ---------------- 2. Install / getting started ----------------
    ("Getting started & installation", "Docs: Installation",
     "Official install guide for every surface (IDE, CLI, Web, Mobile, Crew), including how to update via Command Palette -> 'Kiro: Check for Updates'.",
     "https://kiro.dev/docs/getting-started/installation/", "Official docs"),
    ("Getting started & installation", "Docs: Your first project",
     "Guided first run: set up steering files, build a feature with a spec, automate with hooks, extend with MCP servers.",
     "https://kiro.dev/docs/getting-started/first-project/", "Official docs"),
    ("Getting started & installation", "Docs: Learn by playing (tutorial series)",
     "Hands-on multi-part tutorial that teaches Kiro by modifying a sample game codebase (Spirit of Kiro).",
     "https://kiro.dev/docs/guides/learn-by-playing/", "Official tutorial"),
    ("Getting started & installation", "Tutorial: Steering Kiro and improving the homepage",
     "Tutorial step showing the 'Kiro: Generate project steering documents' command from the Command Palette (Ctrl/Cmd+Shift+P).",
     "https://kiro.dev/docs/guides/learn-by-playing/01-improve-the-homepage/", "Official tutorial"),
    ("Getting started & installation", "Tutorial: Managing game assets with agent hooks",
     "Tutorial step for creating your first hook from the Kiro panel (ghost icon) in the sidebar.",
     "https://kiro.dev/docs/guides/learn-by-playing/06-managing-assets-with-agent-hooks/", "Official tutorial"),
    ("Getting started & installation", "Tutorial: Extending Kiro with MCP",
     "Tutorial step for adding an MCP server from the Kiro panel's 'MCP Servers' section.",
     "https://kiro.dev/docs/guides/learn-by-playing/07-extending-kiro-with-mcp/", "Official tutorial"),
    ("Getting started & installation", "Guide: How to download and install Kiro (Mac, Windows, Linux)",
     "Community walkthrough of the whole path from download to first working spec, with rough time estimates for each step.",
     "https://pingax.com/kiro-download-install-setup/", "Community blog"),
    ("Getting started & installation", "Complete Kiro guide: what it is, features, pricing, setup",
     "Long-form community overview combining feature explanations, pricing tiers and setup steps in one article.",
     "https://pingax.com/kiro-aws-complete-guide/", "Community blog"),
    ("Getting started & installation", "Official IDE and CLI install guide for Windows, macOS, Linux",
     "Community install guide that tracks concrete release versions and lists the available installer variants per platform.",
     "https://rottenwifi.com/amazon-kiro-download-official-ide-and-cli-install-guide-for-windows-macos-and-linux/", "Community blog"),
    ("Getting started & installation", "How to download the Kiro AI IDE (no waitlist)",
     "Walkthrough of getting Kiro installed and signed in without waiting for an invite.",
     "https://apidog.com/blog/download-kiro-ai-ide/", "Community blog"),
    ("Getting started & installation", "Kiro IDE for Windows: features, pricing and download",
     "Windows-focused introduction explaining the plan-before-code workflow for newcomers.",
     "https://www.windowsmode.com/kiro-ide-on-windows/", "Community blog"),
    ("Getting started & installation", "How to download and use AWS Kiro IDE",
     "Beginner article noting Kiro is a Visual Studio Code fork, so the editor feels familiar while adding agentic workflows.",
     "https://www.cromacampus.com/blogs/how-to-download-and-use-aws-kiro-ide/", "Community blog"),
    ("Getting started & installation", "Como instalar e configurar o Kiro IDE (Portuguese)",
     "Portuguese-language install and configuration guide covering download, sign-in options and first setup.",
     "https://uds.com.br/blog/como-instalar-configurar-kiro-ide/", "Community blog"),
    ("Getting started & installation", "Installing Kiro: from download to first launch (Japanese, EN toggle)",
     "Screenshot-heavy install diary; the download button auto-detects your OS. Part of a broader Kiro learning series.",
     "https://note.com/ai_tech_notes/n/n28c54f8d171b?hl=en", "Community blog"),
    ("Getting started & installation", "Gist: Kiro IDE on Ubuntu 22.04",
     "Notes on getting Kiro running on older Ubuntu, including library/spdlog style errors and workarounds.",
     "https://gist.github.com/Chen188/b6d04ccd843c6471629c05d48f8003e7", "Gist / notes"),
    ("Getting started & installation", "Kiro IDE + WSL setup notes",
     "Explains that Kiro is a Code OSS fork, so Microsoft's proprietary Remote-WSL extension is not available, and what to do instead.",
     "https://github.com/rommelporras/kiro-config/blob/main/docs/setup/kiro-ide-wsl-setup.md", "GitHub"),
    ("Getting started & installation", "Kiro IDE on Windows: WSL2 support via Open Remote extension",
     "Workaround for reaching WSL2 filesystems, toolchains and MCP servers from Kiro on Windows using the open-source remote extension.",
     "https://mcgarrah.org/kiro-ide-wsl2-support-open-remote-extension/", "Community blog"),
    ("Getting started & installation", "Kiro getting-started repo with AWS docs and search MCPs",
     "Sample setup repo that wires Kiro up with AWS documentation, AWS knowledge and Brave Search MCP servers.",
     "https://github.com/rushealy-aws/kiro-getting-started", "GitHub"),

    # ---------------- 3. Spec-driven development ----------------
    ("Spec-driven development (SDD)", "Docs: Specs",
     "Reference for specs - structured artifacts that formalise feature and bug work, turning high-level ideas into tracked implementation plans.",
     "https://kiro.dev/docs/specs/", "Official docs"),
    ("Spec-driven development (SDD)", "Docs: Spec best practices",
     "Practical advice on writing good specs, importing requirements through MCP servers, and the fact that a spec's workflow is chosen at creation time.",
     "https://kiro.dev/docs/specs/best-practices/", "Official docs"),
    ("Spec-driven development (SDD)", "Docs: Correctness (property-based testing)",
     "How Kiro turns natural-language requirements into executable properties and generates test cases from them.",
     "https://kiro.dev/docs/specs/correctness/", "Official docs"),
    ("Spec-driven development (SDD)", "Docs: Specs in the CLI",
     "Using the built-in Spec agent from the terminal - reason about requirements and design first, then execute the plan with verification between tasks.",
     "https://kiro.dev/docs/cli/v3/specs/", "Official docs"),
    ("Spec-driven development (SDD)", "Docs: Specs in Kiro Web",
     "The same requirements/design/tasks workflow in the browser, with the agent implementing the plan and opening a pull request.",
     "https://kiro.dev/docs/web/specs/", "Official docs"),
    ("Spec-driven development (SDD)", "Blog: Kiro and the future of AI spec-driven development",
     "Conceptual essay on why declaring the desired outcome (the SQL analogy) beats step-by-step prompting.",
     "https://kiro.dev/blog/kiro-and-the-future-of-software-development/", "Official blog"),
    ("Spec-driven development (SDD)", "Blog: Does your code match your spec?",
     "Deep dive on property-based testing: requirements become an executable specification used to check generated code.",
     "https://kiro.dev/blog/property-based-testing/", "Official blog"),
    ("Spec-driven development (SDD)", "GitHub: Kiro system prompts and spec process guide",
     "Community-collected system prompts plus a written guide to the three-phase process: Requirements, Design, Tasks.",
     "https://github.com/jasonkneen/kiro", "GitHub"),
    ("Spec-driven development (SDD)", "Spec process guide: methodology overview",
     "Explains spec-driven development as planning-first engineering with documentation and structured implementation.",
     "https://github.com/jasonkneen/kiro/blob/main/spec-process-guide/methodology/overview.md", "GitHub"),
    ("Spec-driven development (SDD)", "Spec process guide: tasks phase",
     "How an approved design is converted into discrete, actionable coding tasks - the final phase of the spec workflow.",
     "https://github.com/jasonkneen/kiro/blob/main/spec-process-guide/process/tasks-phase.md", "GitHub"),
    ("Spec-driven development (SDD)", "Steering doc template for Kiro specs (promptz.lib)",
     "Reusable steering document describing how to leverage specs consistently across a project.",
     "https://github.com/cremich/promptz.lib/blob/main/steering/kiro-specs.md", "GitHub"),
    ("Spec-driven development (SDD)", "Hands-on tutorial: build a full-stack app with Kiro specs",
     "Full tutorial repo that teaches the spec workflow by building a QR code web portal end to end.",
     "https://github.com/qinjie/get-started-with-kiro", "GitHub"),
    ("Spec-driven development (SDD)", "re:Post: Kiro beyond a coding assistant - full-stack SDD",
     "Detailed AWS re:Post article on the spec-driven methodology, sign-in options and the fact that Kiro is stack- and cloud-agnostic.",
     "https://repost.aws/articles/AROjWKtr5RTjy6T2HbFJD_Mw/kiro-agentic-ai-ide-beyond-a-coding-assistant-full-stack-software-development-with-spec-driven-ai", "AWS re:Post"),

    # ---------------- 4. Steering / configuration ----------------
    ("Steering & configuration", "Docs: Steering",
     "Core reference: markdown files that give Kiro persistent project knowledge so conventions, libraries and standards are followed without re-explaining them.",
     "https://kiro.dev/docs/steering/", "Official docs"),
    ("Steering & configuration", "Docs: Steering for Crew agents",
     "How steering rules apply to every session launched from a workspace - the recommended way to add project context without editing agent configs.",
     "https://kiro.dev/docs/crew/capabilities/steering/", "Official docs"),
    ("Steering & configuration", "Blog: Stop repeating yourself - global steering",
     "Argues for steering as a persistent AI context layer holding your preferences, standards and decisions.",
     "https://kiro.dev/blog/stop-repeating-yourself/", "Official blog"),
    ("Steering & configuration", "Blog: Teaching Kiro new tricks with steering and MCP",
     "Shows how files in .kiro/steering/ shape every interaction in a workspace, combined with MCP for extra capabilities.",
     "https://kiro.dev/blog/teaching-kiro-new-tricks-with-agent-steering-and-mcp/", "Official blog"),
    ("Steering & configuration", "Steering complete guide: always, fileMatch, manual modes",
     "Community deep dive on the three inclusion modes with concrete configuration examples for per-project agent behaviour.",
     "https://note.com/ai_tech_notes/n/na77dcd296f9e?hl=en", "Community blog"),
    ("Steering & configuration", "Medium: Kiro steering guide",
     "Short introduction to what steering is and how it keeps the agent aligned with established patterns.",
     "https://medium.com/@vampirenalan/kiro-steering-guide-7800966d2c99", "Medium"),
    ("Steering & configuration", "AWS samples: Kiro CLI steering prompts for product teams",
     "Official AWS sample repo of steering files that provide context, workflows and constraints for non-engineering workflows.",
     "https://github.com/aws-samples/sample-kiro-cli-prompts-for-product-teams", "GitHub (AWS samples)"),
    ("Steering & configuration", "Community collection of Kiro steering documents",
     "Grab-bag of ready-made steering docs you can copy into .kiro/steering/.",
     "https://github.com/mikeartee/kiro-steering-docs", "GitHub"),
    ("Steering & configuration", "dev.to: Steering Kiro to completion - less effort, less stress",
     "Practitioner write-up on combining the spec workflow with steering files so the agent plans and executes with less babysitting.",
     "https://dev.to/truger/steering-kiro-to-completion-less-effort-less-stress-o27", "dev.to"),
    ("Steering & configuration", "Kiro best-practices boilerplate",
     "Opinionated bundle of steering documents and agent hooks that enforce standards and automate quality checks.",
     "https://github.com/awsdataarchitect/kiro-best-practices", "GitHub"),
    ("Steering & configuration", "kiro-config: steering docs, hooks, MCP configs and spec templates",
     "Another full .kiro/ configuration collection covering steering, hooks, MCP servers and spec templates.",
     "https://github.com/mehtadman87/kiro-config", "GitHub"),
    ("Steering & configuration", "Kiro project template (40+ steering docs, 34 hooks, CLI scaffolder)",
     "Large opinionated template that scaffolds a production-ready .kiro/ directory in one command.",
     "https://github.com/BinarySword/kiro-project-template", "GitHub"),

    # ---------------- 5. Hooks ----------------
    ("Hooks & automation", "Docs: Hooks",
     "Reference for hooks - run shell commands or agent prompts automatically when files change, tools are invoked, or tasks complete.",
     "https://kiro.dev/docs/hooks/", "Official docs"),
    ("Hooks & automation", "Docs: Hooks in CLI v3",
     "The v3 hook format: standalone versioned files in .kiro/hooks/, two action types, and lifecycle triggers for specs, deletion and manual runs.",
     "https://kiro.dev/docs/cli/v3/hooks/", "Official docs"),
    ("Hooks & automation", "Docs: Hooks in the Crew UI",
     "Managing hooks from the browser: view, create, edit and delete, each showing its trigger, action and optional matcher.",
     "https://kiro.dev/docs/crew/capabilities/hooks/", "Official docs"),
    ("Hooks & automation", "Blog: Automate your workflow with agent hooks",
     "Introduction to hooks as AI-powered triggers that update tests, sync docs and apply standards as you code.",
     "https://kiro.dev/blog/automate-your-development-workflow-with-agent-hooks/", "Official blog"),
    ("Hooks & automation", "How to use Kiro hooks to enforce IaC standards",
     "Practical hook examples, plus when to prefer a shell command action versus sending a prompt back to the agent.",
     "https://www.ducea.com/2025/10/12/howto-use-kiro-hooks-to-enforce-iac-standards/", "Community blog"),
    ("Hooks & automation", "Tutorial: hooks, steering and custom agents deep dive",
     "Long tutorial tying the three configuration features together, e.g. running tests the moment a spec changes and scoping agents to one job.",
     "https://lablab.ai/ai-tutorials/aws-kiro-hooks-steering-custom-agents-deep-dive", "Tutorial site"),
    ("Hooks & automation", "Docs: IDE 0.x reference (legacy hook UI, palette commands)",
     "Reference for older IDE versions, including opening the hook UI via 'Kiro: Open Kiro Hook UI' in the Command Palette.",
     "https://kiro.dev/docs/ide/0x-reference/", "Official docs"),

    # ---------------- 6. MCP ----------------
    ("MCP & extensibility", "Docs: MCP overview",
     "What MCP adds to Kiro and how to open the workspace or user MCP config JSON from the Command Palette.",
     "https://kiro.dev/docs/mcp/", "Official docs"),
    ("MCP & extensibility", "Docs: MCP configuration reference",
     "Detailed configuration-file structure, server setup and management of local and remote MCP servers across all surfaces.",
     "https://kiro.dev/docs/mcp/configuration/", "Official docs"),
    ("MCP & extensibility", "Docs: MCP governance / allow-list",
     "Enterprise control: publish a JSON allow-list over HTTPS and attach the URL to a Kiro profile to restrict which MCP servers users may add.",
     "https://kiro.dev/docs/enterprise/governance/mcp/", "Official docs"),
    ("MCP & extensibility", "Gist: MCP servers setup guide for Kiro IDE",
     "Step-by-step community setup for common servers (git operations, web fetch, GitHub integration).",
     "https://gist.github.com/sai-praveen-os/fba20bbd45fb167e8d6637d5e9dfe086", "Gist / notes"),
    ("MCP & extensibility", "SonarQube MCP server in Kiro (vendor docs)",
     "Vendor documentation for connecting SonarQube's local MCP server to Kiro's agents. Note their warning that only user tokens work for the binding.",
     "https://docs.sonarsource.com/sonarqube-for-vs-code/ai-capabilities/ides/kiro", "Vendor docs"),
    ("MCP & extensibility", "Set up the SonarQube power for Kiro",
     "Vendor guide to the SonarQube power: the MCP server syncs analyzer plugins locally while issues, measures and quality gates come from your connected instance.",
     "https://www.sonarsource.com/resources/library/set-up-the-sonarqube-power-for-kiro/", "Vendor docs"),
    ("MCP & extensibility", "SonarQube MCP server quickstart (all IDEs)",
     "Top-level quickstart covering the three supported user configurations if the Kiro-specific page moves.",
     "https://docs.sonarsource.com/sonarqube-mcp-server/quickstart-guide", "Vendor docs"),
    ("MCP & extensibility", "AWS Agent Toolkit quick start",
     "Installing the AWS agent plugin that bundles the AWS MCP server configuration and curated agent skills in one step.",
     "https://docs.aws.amazon.com/agent-toolkit/latest/userguide/quick-start.html", "AWS docs"),
    ("MCP & extensibility", "re:Post: Install Kiro + Agent Toolkit for AWS",
     "Walkthrough for using Kiro together with the AWS Agent Toolkit to build, deploy and manage AWS environments.",
     "https://repost.aws/articles/AReLJ1UhxdTzqXP-h421MFCg/install-kiro-and-agent-toolkit-for-aws-to-build-deploy-and-manage-your-aws-environment", "AWS re:Post"),

    # ---------------- 7. Custom agents, powers ----------------
    ("Custom agents & Powers", "Docs: Custom agents",
     "Define agents with their own tool access, permissions and context so behaviour is tailored per use case.",
     "https://kiro.dev/docs/custom-agents/", "Official docs"),
    ("Custom agents & Powers", "GitHub: kirodotdev/powers",
     "Official Powers registry. Powers add specialised context and tools on demand instead of loading every MCP server up front.",
     "https://github.com/kirodotdev/powers", "GitHub"),
    ("Custom agents & Powers", "Changelog 0.7: Powers, auto summarisation, slash commands",
     "Release notes introducing Powers as reusable bundles of MCP servers, steering files and hooks that activate from conversation context.",
     "https://kiro.dev/changelog/ide/0-7/", "Official changelog"),
    ("Custom agents & Powers", "Changelog 0.8: web tools, subagents, contextual hooks, per-file review",
     "Adds per-file accept/reject review of multi-file changes in both vibe and spec sessions.",
     "https://kiro.dev/changelog/ide/0-8/", "Official changelog"),
    ("Custom agents & Powers", "Changelog 0.10: new spec workflows, hunk-based edits, task hooks",
     "Supervised mode moves to hunk-level diffs you can accept, reject or discuss with inline chat.",
     "https://kiro.dev/changelog/ide/0-10/", "Official changelog"),
    ("Custom agents & Powers", "Changelog 0.6: spec correctness, checkpointing, multi-root workspaces",
     "Adds enterprise billing, reverting to a previous conversation via checkpoints, multi-root workspace support and property-based testing.",
     "https://kiro.dev/changelog/ide/0-6/", "Official changelog"),
    ("Custom agents & Powers", "AWS blog: Kiro power for the AWS DevOps Agent",
     "How a Kiro power plugs cloud-operations expertise into the agent.",
     "https://aws.amazon.com/blogs/devops/supercharge-your-cloud-operations-with-the-kiro-power-for-aws-devops-agent/", "AWS blog"),
    ("Custom agents & Powers", "AWS blog: AI-driven delivery with Kiro, DevOps Agent and Dynatrace",
     "End-to-end delivery pipeline example combining Kiro with observability tooling.",
     "https://aws.amazon.com/blogs/devops/ai-driven-software-delivery-with-kiro-aws-devops-agent-and-bluebox-by-dynatrace/", "AWS blog"),

    # ---------------- 8. CLI & Crew ----------------
    ("CLI & Crew", "Docs: Kiro CLI setup and first run",
     "Getting productive in the terminal agent: it reads your codebase, writes code, runs commands and asks before destructive actions.",
     "https://kiro.dev/docs/cli/setup/", "Official docs"),
    ("CLI & Crew", "Docs: What's new in CLI 3.0",
     "Summary of the v3 CLI, including the Spec agent and starting a spec with '/spec new <name>'.",
     "https://kiro.dev/docs/cli/v3/", "Official docs"),
    ("CLI & Crew", "Docs: CLI context management",
     "What context is included automatically (working directory, OS) and how to add more.",
     "https://kiro.dev/docs/cli/chat/context/", "Official docs"),
    ("CLI & Crew", "Docs: Crew",
     "Kiro's personal-agent surface. First launch on localhost guides you through installing kiro-cli and signing in.",
     "https://kiro.dev/docs/crew/", "Official docs"),
    ("CLI & Crew", "Docs: Crew Discord interface",
     "Running Kiro through Discord DMs with isolated sessions, inline tool approval and a deny-by-default allowlist.",
     "https://kiro.dev/docs/crew/interfaces/discord/", "Official docs"),
    ("CLI & Crew", "Kiro CLI in a cloud shell (no local install)",
     "Using the CLI from AWS CloudShell or any Linux browser terminal: install, authenticate, run a first agentic session.",
     "https://pjay1010.medium.com/kiro-cli-in-a-cloud-shell-using-kiro-without-a-local-install-cd0f3168aa45", "Medium"),
    ("CLI & Crew", "awslabs CLI Agent Orchestrator: Kiro CLI provider",
     "How to drive Kiro CLI from an orchestrator using agent profiles - useful for multi-agent automation.",
     "https://github.com/awslabs/cli-agent-orchestrator/blob/main/docs/kiro-cli.md", "GitHub (awslabs)"),
    ("CLI & Crew", "Kiro CLI notes compiled from tutorial videos",
     "Community notes distilled from a series of Kiro CLI videos, with attribution to the original creators.",
     "https://github.com/chasko-labs/kiro-cli-notes", "GitHub"),

    # ---------------- 9. IDE usage ----------------
    ("Using the IDE day to day", "Docs: Chat panel",
     "Natural-language chat over your codebase - ask questions, generate features, debug - with project context maintained. Also lists supported chat languages.",
     "https://kiro.dev/docs/ide/chat/", "Official docs"),
    ("Using the IDE day to day", "Docs: Autopilot mode",
     "Kiro's autonomous execution mode: broad codebase changes and complex tasks with minimal intervention.",
     "https://kiro.dev/docs/ide/chat/autopilot/", "Official docs"),
    ("Using the IDE day to day", "Docs: IDE interface tour",
     "Layout and panels of the editor, and where the AI features live.",
     "https://kiro.dev/docs/ide/editor/interface/", "Official docs"),
    ("Using the IDE day to day", "Complete guide to '#' context features",
     "How typing '#' in chat attaches files, folders, terminal output, git diffs and library docs - the fastest accuracy win.",
     "https://note.com/ai_tech_notes/n/n3eb8aac859ce?hl=en", "Community blog"),
    ("Using the IDE day to day", "Docs: Models",
     "Which frontier and open-weight models are available, and how the tiers trade agentic performance against cost.",
     "https://kiro.dev/docs/models/", "Official docs"),
    ("Using the IDE day to day", "Blog: Empowering Kiro with IDE diagnostics",
     "How Kiro consumes editor diagnostics (the red squiggles) as immediate feedback on code correctness.",
     "https://kiro.dev/blog/empowering-kiro-with-ide-diagnostics/", "Official blog"),
    ("Using the IDE day to day", "Kiro workshop: kicking things off",
     "Workshop step covering the chat panel shortcut (Cmd+L / Ctrl+L) and the basic interaction loop.",
     "https://github.com/salihgueler/kiro-workshop/blob/main/steps/1_kicking_things_off.md", "GitHub"),
    ("Using the IDE day to day", "Kiro AI: a guide with practical examples",
     "Tutorial framing Kiro as the alternative to prompt-until-it-works: structured plans, decomposed features, focused agents.",
     "https://www.datacamp.com/tutorial/kiro-ai", "Tutorial site"),

    # ---------------- 10. Web / Mobile / cloud sessions ----------------
    ("Web, Mobile & cloud sessions", "Docs: Kiro Web overview",
     "The two Web modes - collaborative by default, or autonomous where the agent plans, implements and opens a PR itself.",
     "https://kiro.dev/docs/web/", "Official docs"),
    ("Web, Mobile & cloud sessions", "Docs: Kiro Web setup",
     "Preview availability and the admin prerequisite: Cloud Sessions must be enabled in Kiro Settings in the configured AWS account.",
     "https://kiro.dev/docs/web/setup/", "Official docs"),
    ("Web, Mobile & cloud sessions", "Docs: Working with the agent in Web",
     "Day-to-day Web usage, plus data retention: sessions expire after 90 days and chat/logs are deleted (PRs and commits are unaffected).",
     "https://kiro.dev/docs/web/using-the-agent/", "Official docs"),
    ("Web, Mobile & cloud sessions", "Docs: Autonomous mode",
     "The agent asks clarifying questions upfront, plans, delegates to sub-agents and opens a PR when done.",
     "https://kiro.dev/docs/web/autonomous-mode/", "Official docs"),
    ("Web, Mobile & cloud sessions", "Docs: Cloud sessions",
     "The shared execution environment behind Web and Mobile that the IDE and CLI can also create and attach to.",
     "https://kiro.dev/docs/cloud-sessions/", "Official docs"),

    # ---------------- 11. Pricing, credits, models ----------------
    ("Pricing, credits & models", "Pricing page",
     "Current tiers: a perpetual free tier with limited credits, then Pro, Pro+, Pro Max and Power for higher capacity.",
     "https://kiro.dev/pricing/", "Official site"),
    ("Pricing, credits & models", "Blog: Understanding Kiro's pricing - specs, vibes, usage tracking",
     "Explains what counts as a spec request versus a vibe request and how usage is tracked.",
     "https://kiro.dev/blog/understanding-kiro-pricing-specs-vibes-usage-tracking/", "Official blog"),
    ("Pricing, credits & models", "Blog: New pricing plans and Auto",
     "Announcement of unified limits - one credit pool instead of separate vibe and spec allowances - plus the Auto agent.",
     "https://kiro.dev/blog/new-pricing-plans-and-auto/", "Official blog"),
    ("Pricing, credits & models", "Blog: Kiro pricing plans are now live",
     "Details of the launch pricing and the welcome bonus of extra spec and vibe requests in the first 14 days.",
     "https://kiro.dev/blog/pricing-plans-are-live/", "Official blog"),
    ("Pricing, credits & models", "Blog: Pricing update and waitlist invites",
     "Earlier pricing update, including trial bonus details for new users.",
     "https://kiro.dev/blog/pricing-waitlist-updates/", "Official blog"),
    ("Pricing, credits & models", "Free tier vs Pro vs Pro Max compared",
     "Community comparison of interaction allowances per tier and which tier suits which workload.",
     "https://pingax.com/kiro-pricing-free-tier/", "Community blog"),
    ("Pricing, credits & models", "Kiro review: pricing, features, pros and cons",
     "Balanced third-party review of the spec-driven approach and what you get for the money.",
     "https://vibecoding.app/blog/kiro-review", "Community blog"),
    ("Pricing, credits & models", "OpenAI: GPT-5.6 in Kiro",
     "Model-provider perspective on how Kiro's structured requirements and designs feed the model better context.",
     "https://openai.com/index/gpt-5-6-in-kiro/", "Vendor blog"),
    ("Pricing, credits & models", "re:Post: AWS Activate credits for the Kiro Power plan",
     "Question thread on whether AWS Activate credits cover a Kiro subscription or whether you are billed directly.",
     "https://repost.aws/questions/QU-tEyD7NyTvC2JxLeMLD6-A/aws-activate-credits-eligibility-for-kiro-power-subscription-plan", "AWS re:Post"),
    ("Pricing, credits & models", "re:Post knowledge center: track Kiro usage",
     "Official guidance on checking usage from account settings, the IDE status bar, a CLI command, or org-wide via the Kiro console dashboard and reports.",
     "https://www.repost.aws/knowledge-center/kiro-track-usage", "AWS re:Post"),
    ("Pricing, credits & models", "re:Post: Why can't I use Claude in Kiro?",
     "Troubleshooting model availability, including AWS Region mismatches when routing through Bedrock.",
     "https://repost.aws/questions/QU51POdpb3RSqEoXok-x93CA/why-can-i-use-claude-in-kiro", "AWS re:Post"),

    # ---------------- 12. Enterprise / security ----------------
    ("Enterprise, security & governance", "Docs: Privacy and security",
     "Data handling plus the difference between Autopilot and Supervised interaction modes (same capabilities, different review points).",
     "https://kiro.dev/docs/privacy-and-security/", "Official docs"),
    ("Enterprise, security & governance", "Docs: Enterprise onboarding quickstart",
     "Create a profile in the Kiro console and subscribe users - the profile ties identities to subscriptions and settings.",
     "https://kiro.dev/docs/enterprise/getting-started/", "Official docs"),
    ("Enterprise, security & governance", "Docs: Subscribe your team",
     "Admin prerequisites and the minimum IAM permissions needed to subscribe and manage Kiro users.",
     "https://kiro.dev/docs/enterprise/subscribe/", "Official docs"),
    ("Enterprise, security & governance", "Docs: Enterprise IAM permissions",
     "The IAM policies required to reach the Kiro console and manage a subscription.",
     "https://kiro.dev/docs/enterprise/iam/", "Official docs"),
    ("Enterprise, security & governance", "Docs: Connect IAM Identity Center as your IdP",
     "Enabling IAM Identity Center, adding users, or federating an external identity provider for Kiro sign-in.",
     "https://kiro.dev/docs/enterprise/identity-provider/iam-identity-center/", "Official docs"),
    ("Enterprise, security & governance", "re:Post: Kiro enterprise governance and operations guide",
     "Administrator-oriented guide to Kiro concepts, governance considerations and how to operate Kiro in an organisation.",
     "https://repost.aws/articles/ARp46l5grvQPi-aDJ7UVh8xA/kiro-enterprise-governance-and-operations-guide-for-kiro-administrators", "AWS re:Post"),
    ("Enterprise, security & governance", "How to set up Kiro users in AWS IAM Identity Center",
     "Practical tutorial for managing Kiro users through SSO so billing ties to your AWS account and no extra credentials are needed.",
     "https://www.playingaws.com/tutorials/how-to-set-up-kiro-users-in-aws-iam-identity-center/", "Community blog"),
    ("Enterprise, security & governance", "dev.to: Deploying Kiro securely in the enterprise",
     "Covers identity, feature controls and AI governance, including admin control over which models and MCP integrations are allowed.",
     "https://dev.to/bhatiagirish/deploying-kiro-ide-securely-in-the-enterprise-identity-feature-controls-and-ai-governance-ehp", "dev.to"),
    ("Enterprise, security & governance", "How to give Kiro safe access to your AWS environment",
     "Recommends SSO-assumed roles with short-lived credentials over long-lived access keys, with CloudTrail attribution.",
     "https://www.ducea.com/2026/03/07/howto-give-kiro-safe-access-to-your-aws-environment/", "Community blog"),
    ("Enterprise, security & governance", "Getting started with Kiro: integrating IAM Identity Center (Japanese)",
     "Japanese-language walkthrough of the Kiro console team setup flow.",
     "https://www.qes.co.jp/media/aws/Kiro/a763", "Community blog"),

    # ---------------- 13. Official troubleshooting ----------------
    ("Troubleshooting - official", "Docs: IDE troubleshooting",
     "The main official troubleshooting page. Covers macOS 'Kiro is damaged' Gatekeeper prompts and corporate TLS inspection breaking connections for some users only.",
     "https://kiro.dev/docs/ide/troubleshooting/", "Official docs (troubleshooting)"),
    ("Troubleshooting - official", "Docs: Custom agent troubleshooting",
     "Diagnosing misconfigured custom agents (tools, permissions, context).",
     "https://kiro.dev/docs/custom-agents/troubleshooting/", "Official docs (troubleshooting)"),
    ("Troubleshooting - official", "Docs: Crew troubleshooting",
     "Most Crew issues reduce to a single shell command fix; includes container sandbox permissions.",
     "https://kiro.dev/docs/crew/troubleshooting/", "Official docs (troubleshooting)"),
    ("Troubleshooting - official", "GitHub: kirodotdev/Kiro issue tracker",
     "Where bugs are reported and triaged. Search here first - most problems already have a thread with workarounds.",
     "https://github.com/kirodotdev/Kiro/issues", "GitHub issues"),

    # ---------------- 14. Known problems - community threads ----------------
    ("Known problems & fixes", "Issue #318: terminal / command line gets stuck",
     "Commonly caused by complex zsh prompts (Powerlevel10k, powerline), precmd hooks, starship or direnv altering stdout/TTY behaviour. Simplify the prompt to fix.",
     "https://github.com/kirodotdev/Kiro/issues/318", "GitHub issue"),
    ("Known problems & fixes", "Debugging Kiro's terminal blackouts (when exit 0 lies)",
     "Deep technical explanation of shell integration markers and why command output can disappear in VS Code-based agentic editors.",
     "https://griffen.codes/post/kiro-terminal-output-blackouts/", "Community blog"),
    ("Known problems & fixes", "Issue #2814: hangs on 'Working...' after terminal commands",
     "Recurring freeze specifically after the agent runs a terminal command.",
     "https://github.com/kirodotdev/Kiro/issues/2814", "GitHub issue"),
    ("Known problems & fixes", "Issue #1127: agent unresponsive and freezing, no error",
     "Agent freezes on the first tool call with no diagnostic message.",
     "https://github.com/kirodotdev/Kiro/issues/1127", "GitHub issue"),
    ("Known problems & fixes", "Issue #1659: IDE gets stuck with no errors and no response",
     "Chat, model picker and buttons all stop reacting - report includes reproduction context.",
     "https://github.com/kirodotdev/Kiro/issues/1659", "GitHub issue"),
    ("Known problems & fixes", "Issue #2341: application stuck during code generation",
     "Generation stalls with neither completion nor an error such as a network or processing failure.",
     "https://github.com/kirodotdev/Kiro/issues/2341", "GitHub issue"),
    ("Known problems & fixes", "Issue #6004: Kiro stops working and needs a nudge",
     "Hard-to-diagnose permission or API failures that require the user to prompt again to resume.",
     "https://github.com/kirodotdev/Kiro/issues/6004", "GitHub issue"),
    ("Known problems & fixes", "Issue #1191: freezes and severe slowdown on Intel macOS",
     "Works initially, becomes completely unresponsive after extended use on older Intel Macs.",
     "https://github.com/kirodotdev/Kiro/issues/1191", "GitHub issue"),
    ("Known problems & fixes", "Issue #3038: high CPU usage on macOS when idle",
     "CPU and memory stay high after the expected short activity spike.",
     "https://github.com/kirodotdev/Kiro/issues/3038", "GitHub issue"),
    ("Known problems & fixes", "Issue #3416: unbounded memory growth and window crash",
     "Memory climbs until the window crashes - reported around 8 GB on a 32 GB machine.",
     "https://github.com/kirodotdev/Kiro/issues/3416", "GitHub issue"),
    ("Known problems & fixes", "Issue #1435: kiro-agent extension memory leak",
     "MaxListenersExceededWarning points at leaked AbortSignal listeners behind the slowdowns and crashes.",
     "https://github.com/kirodotdev/Kiro/issues/1435", "GitHub issue"),
    ("Known problems & fixes", "Issue #6770: CLI TUI becomes very slow after extended use",
     "Response times and UI interaction degrade within a single long 'kiro-cli chat --tui' session.",
     "https://github.com/kirodotdev/Kiro/issues/6770", "GitHub issue"),
    ("Known problems & fixes", "Issue #9320: send button, cursor and overlay text problems",
     "UI interaction bugs - e.g. the send arrow not responding to clicks so only Enter works.",
     "https://github.com/kirodotdev/Kiro/issues/9320", "GitHub issue"),
    ("Known problems & fixes", "Issue #2561: GitHub sign-in fails on Windows after localhost callback",
     "Login fails despite the callback arriving; suspects network, firewall or proxy interference.",
     "https://github.com/kirodotdev/Kiro/issues/2561", "GitHub issue"),
    ("Known problems & fixes", "Issue #4352: cannot log in with GitHub as OAuth provider",
     "Sign-in failure thread with an associated AWS support case reference.",
     "https://github.com/kirodotdev/Kiro/issues/4352", "GitHub issue"),
    ("Known problems & fixes", "Issue #1712: 'Kiro access not available for this account'",
     "NewUserAccessPausedError during onboarding when access is paused for the account.",
     "https://github.com/kirodotdev/Kiro/issues/1712", "GitHub issue"),
    ("Known problems & fixes", "Issue #4402: 'Your User ID ... temporarily is suspended'",
     "Account lock as a security precaution; resolution goes through AWS support identity verification, not GitHub.",
     "https://github.com/kirodotdev/Kiro/issues/4402", "GitHub issue"),
    ("Known problems & fixes", "Issue #6621: account banned right after subscribing",
     "Maintainers confirm suspensions and appeals are handled by AWS support because they need account-level verification.",
     "https://github.com/kirodotdev/Kiro/issues/6621", "GitHub issue"),
    ("Known problems & fixes", "Issue #816: 'Too many requests' error loop blocks task execution",
     "Repeated retries never succeed, stalling the session.",
     "https://github.com/kirodotdev/Kiro/issues/816", "GitHub issue"),
    ("Known problems & fixes", "Issue #6352: 'Too many requests, please wait before trying again'",
     "Large thread on throttling during peak model demand, with links to related duplicate reports.",
     "https://github.com/kirodotdev/Kiro/issues/6352", "GitHub issue"),
    ("Known problems & fixes", "Issue #8620: persistent 'Too many requests' for 18+ hours on Pro",
     "Long-lived throttled state while credits remain available.",
     "https://github.com/kirodotdev/Kiro/issues/8620", "GitHub issue"),
    ("Known problems & fixes", "Issue #9271: throttled despite having hundreds of credits",
     "Same throttling symptom reported with a healthy credit balance.",
     "https://github.com/kirodotdev/Kiro/issues/9271", "GitHub issue"),
    ("Known problems & fixes", "Issue #8001: persistent HTTP 429 after an account unban",
     "Rate limits do not return to baseline after a false-positive suspension is lifted.",
     "https://github.com/kirodotdev/Kiro/issues/8001", "GitHub issue"),
    ("Known problems & fixes", "Issue #5690: MCP OAuth fails with \"missing field 'scopes'\"",
     "CLI cannot load a remote MCP server because the OAuth metadata response lacks a scopes field.",
     "https://github.com/kirodotdev/Kiro/issues/5690", "GitHub issue"),
    ("Known problems & fixes", "Gist: \"Cannot read properties of undefined (reading 'model')\"",
     "Notes tracing this error to the model selection/configuration path in the Kiro agent extension.",
     "https://gist.github.com/Chen188/fde7c272cab4980a68b744cad7035c91", "Gist / notes"),
    ("Known problems & fixes", "Issue #2308: billing not available in all countries",
     "Feature request/bug report about payment restrictions blocking paying customers in some regions.",
     "https://github.com/kirodotdev/Kiro/issues/2308", "GitHub issue"),
    ("Known problems & fixes", "Issue #1665: feedback after 15 days of use",
     "Extended real-world critique - a good sanity check on rough edges before you commit a team to Kiro.",
     "https://github.com/kirodotdev/Kiro/issues/1665", "GitHub issue"),
    ("Known problems & fixes", "Analysis: the mass account-suspension episode",
     "Critical outside commentary on automated suspensions hitting ordinary development workflows.",
     "https://ludditus.com/2026/03/28/kiro-seems-to-have-gone-amok/", "Community blog"),
    ("Known problems & fixes", "Forum thread: 'Too many requests' after heavy use (Chinese)",
     "Community forum discussion of hitting the throttle under sustained load.",
     "https://linux.do/t/topic/808399", "Forum"),

    # ---------------- 15. Q&A sites ----------------
    ("Q&A: Stack Overflow, re:Post, Quora", "Stack Overflow: all questions tagged 'kiro'",
     "Live feed of Kiro questions on Stack Overflow - bookmark this rather than a single question.",
     "https://stackoverflow.com/questions/tagged/kiro", "Stack Overflow"),
    ("Q&A: Stack Overflow, re:Post, Quora", "Stack Overflow: user ID temporarily suspended / what is kiro.dev",
     "Question about the suspension message and why kiro.dev appears in Amazon Q chat, with community answers.",
     "https://stackoverflow.com/questions/79919889/your-user-id-temporarily-is-suspended-what-is-kiro-dev-and-why-it-appea", "Stack Overflow"),
    ("Q&A: Stack Overflow, re:Post, Quora", "Quora: why does Kiro throw 'too many requests'?",
     "Answer recommending you stop retrying, restart, update, sign out and back in, and avoid VPN/proxy workarounds that make an account look suspicious.",
     "https://www.quora.com/Why-does-Kiro-always-throw-the-error-too-many-requests", "Quora"),
    ("Q&A: Stack Overflow, re:Post, Quora", "AWS re:Post: Kiro tag hub",
     "All re:Post questions and articles tagged Kiro - the closest thing to an official Q&A forum.",
     "https://repost.aws/tags/TAsHlm05XmRIKHHDFpBAPmng/kiro", "AWS re:Post"),
    ("Q&A: Stack Overflow, re:Post, Quora", "Stack Overflow: how to download .vsix files manually",
     "Relevant when an extension is missing from Kiro's registry and you need to sideload it.",
     "https://stackoverflow.com/questions/79359919/how-can-i-manually-download-vsix-files-now-that-the-vs-code-marketplace-no-long", "Stack Overflow"),
    ("Q&A: Stack Overflow, re:Post, Quora", "Stack Overflow: adding missing extensions to a Code OSS build",
     "Approaches for installing extensions that are not in Open VSX - applies to Kiro because it is a Code OSS fork.",
     "https://stackoverflow.com/questions/74672197/how-to-add-extensions-to-vs-codium-open-source-version-from-github-repos", "Stack Overflow"),

    # ---------------- 16. Extensions ----------------
    ("Extensions & marketplace", "Gist: using the VS Code Marketplace in Kiro IDE",
     "Kiro defaults to the Open VSX registry; this note shows the config change (and signature-verification caveat) to reach the Microsoft marketplace. Unsupported - use with care.",
     "https://gist.github.com/ahmedhosnypro/2b70958581896a06edc5e75776c72c57", "Gist / notes"),
    ("Extensions & marketplace", "VSCodium docs: extensions and the Open VSX registry",
     "Background on why some extensions are missing from Code OSS forks and the legitimate options for obtaining them.",
     "https://github.com/VSCodium/vscodium/blob/master/docs/extensions.md", "GitHub"),
    ("Extensions & marketplace", "VS Code extension: Kiro CLI wrapper",
     "Third-party extension that surfaces Kiro CLI inside VS Code; requires the CLI to be installed and authenticated separately.",
     "https://marketplace.visualstudio.com/items?itemName=AsadBinImtiaz.kiro-vscode-extension", "Marketplace"),

    # ---------------- 17. Comparisons ----------------
    ("Comparisons & reviews", "Kiro vs Cursor vs Claude Code: which editor?",
     "Comparison framed around how much control you hand to the agent, and where each tool sits on that spectrum.",
     "https://blog.getbind.co/amazon-kiro-vs-cursor-vs-claude-code-whats-the-best-code-editor-2026/", "Community blog"),
    ("Comparisons & reviews", "Kiro vs Cursor vs Copilot vs Claude Code",
     "Four-way comparison with guidance on common tool pairings for different team types.",
     "https://pingax.com/kiro-vs-cursor-vs-copilot-vs-claude-code/", "Community blog"),
    ("Comparisons & reviews", "Kiro vs Claude Code: benchmarks and plans",
     "Points out the comparison is not apples-to-apples: a full Code OSS-based IDE with a documented spec workflow versus a terminal-native agent.",
     "https://tech-insider.org/kiro-vs-claude-code-2026/", "Community blog"),
    ("Comparisons & reviews", "Kiro vs Cursor: pricing and positioning",
     "Contrasts Kiro's insistence on a written spec before code with Cursor's immediate suggestion loop.",
     "https://tech-insider.org/kiro-vs-cursor-2026/", "Community blog"),
    ("Comparisons & reviews", "Kiro vs Cursor tested on a real production feature",
     "Hands-on comparison: enforced EARS-style requirements, design and task documents versus optional planning.",
     "https://www.augmentcode.com/tools/kiro-vs-cursor", "Community blog"),
    ("Comparisons & reviews", "Amazon Kiro analysis: can a spec-driven IDE replace Claude Code?",
     "Review built from official docs plus community reports, covering EARS requirements, hooks and steering files.",
     "https://www.jangwook.net/en/blog/en/amazon-kiro-spec-driven-ai-ide-vs-claude-code-2026/", "Community blog"),
    ("Comparisons & reviews", "Windsurf alternatives, including Kiro",
     "Positions Kiro as the choice for teams wanting AWS-backed spec-driven development with property-based testing.",
     "https://www.qodo.ai/blog/windsurf-alternatives/", "Vendor blog"),
    ("Comparisons & reviews", "I compared every major AI coding tool",
     "Broad survey of the AI coding tool market with pricing and usage-limit observations.",
     "https://murphye.medium.com/i-compared-every-major-ai-coding-tool-so-you-dont-have-to-f05a6915c0d4", "Medium"),
    ("Comparisons & reviews", "AI coding tool comparison: Copilot, Claude Code, Cursor, Windsurf, Kiro",
     "Comparison article aimed at choosing a primary tool per workflow type.",
     "https://note.com/ai_work_pro/n/n7d8313add149?hl=en", "Community blog"),

    # ---------------- 18. Community ----------------
    ("Community & support channels", "Kiro Discord (official invite page)",
     "The main support channel: ask questions, troubleshoot, and reach the community and the Kiro team.",
     "https://kiro.dev/discord/", "Official community"),
    ("Community & support channels", "Kiro community page",
     "Official hub pointing to Discord and other places to ask questions, share ideas and find collaborators.",
     "https://kiro.dev/community/", "Official community"),
    ("Community & support channels", "Kiro Community Discord server listing",
     "Public server listing describing the official community server, with Kiro engineering and product staff present.",
     "https://discord.com/servers/1374034175430230016", "Discord"),
    ("Community & support channels", "kirocommunity.com",
     "Community-run Q&A and support site for all experience levels.",
     "https://kirocommunity.com/", "Community site"),
    ("Community & support channels", "awesome-kiro (kirodotdev-labs)",
     "Community-curated list of steerings, skills, hooks, orchestrators, extensions and plugins. Not officially endorsed - inclusion is not an endorsement.",
     "https://github.com/kirodotdev-labs/awesome-kiro", "GitHub"),
    ("Community & support channels", "awesome-kiro (friends-of-kiro)",
     "Alternative curated resource list for Kiro, including pointers to official Discord support channels.",
     "https://github.com/friends-of-kiro/awesome-kiro", "GitHub"),
    ("Community & support channels", "awesome-kiro (hololeo)",
     "Another curated link collection of Kiro tutorials and resources.",
     "https://github.com/hololeo/awesome-kiro", "GitHub"),
    ("Community & support channels", "promptz.lib - community library",
     "Shared prompts, powers, custom agents, hooks and steering documents contributed by Kiro users.",
     "https://github.com/cremich/promptz.lib", "GitHub"),
    ("Community & support channels", "Kiro quickstart / project template (Dynamous)",
     "Quickstart template and project scaffold, also used as a hackathon starting point.",
     "https://github.com/0xkgt/starting-point", "GitHub"),
    ("Community & support channels", "Kiro workshop repository",
     "Step-by-step workshop material you can run yourself or use to onboard a team.",
     "https://github.com/salihgueler/kiro-workshop", "GitHub"),
    ("Community & support channels", "Tutorial repo: hooks, steering and custom agents (source)",
     "Markdown source of the deep-dive tutorial, handy for reading offline or reusing snippets.",
     "https://github.com/lablab-ai/community-content/blob/main/tutorials/en/aws-kiro-hooks-steering-custom-agents-deep-dive.mdx", "GitHub"),
]


# =====================================================================
# Second research pass - additional resources
# =====================================================================

ROWS += [
    # ---------------- Reference docs not covered above ----------------
    ("Reference & configuration", "Docs: How Kiro works",
     "Explains the single unified agent harness behind the IDE, CLI, Web and Mobile, and why your setup travels between them.",
     "https://kiro.dev/docs/how-kiro-works/", "Official docs"),
    ("Reference & configuration", "Docs: Configuration scopes",
     "The layered config model - global (~/.kiro/), project (.kiro/) and agent scope - plus a full table of which file lives where and which scope wins.",
     "https://kiro.dev/docs/configuration/", "Official docs"),
    ("Reference & configuration", "Docs: Permissions",
     "Capability-based access control. Worth reading before you loosen anything: deny rules win over allow rules in every scope.",
     "https://kiro.dev/docs/permissions/", "Official docs"),
    ("Reference & configuration", "Docs: Keyboard shortcuts",
     "The IDE shortcut reference, organised by category.",
     "https://kiro.dev/docs/reference/keyboard-shortcuts/", "Official docs"),
    ("Reference & configuration", "Docs: Slash commands",
     "In-chat commands that trigger actions without leaving the conversation.",
     "https://kiro.dev/docs/reference/slash-commands/", "Official docs"),
    ("Reference & configuration", "Docs: CLI command reference",
     "Every kiro-cli command and flag, including how arguments are forwarded to Crew.",
     "https://kiro.dev/docs/reference/cli-commands/", "Official docs"),
    ("Reference & configuration", "Docs: Settings reference",
     "Configurable settings from telemetry to chat behaviour, key bindings and feature toggles.",
     "https://kiro.dev/docs/reference/settings/", "Official docs"),
    ("Reference & configuration", "Docs: Exit codes",
     "Exit-code meanings - essential if you script Kiro or run it in a pipeline.",
     "https://kiro.dev/docs/reference/exit-codes/", "Official docs"),
    ("Reference & configuration", "Docs: In-session settings (/settings)",
     "Change colours, key bindings, multi-line input and prompt-history scope from inside a chat session.",
     "https://kiro.dev/docs/cli/chat/settings/", "Official docs"),
    ("Reference & configuration", "Docs: Agent configuration reference",
     "Every field of an agent config for IDE 1.0 / CLI 3.0, what replaced the deprecated toolsSettings, and the /upgrade-agent migration command.",
     "https://kiro.dev/docs/custom-agents/configuration-reference/", "Official docs"),
    ("Reference & configuration", "Docs: Creating custom agents",
     "Practical guide to defining an agent's tools, permissions and auto-included context.",
     "https://kiro.dev/docs/custom-agents/creating/", "Official docs"),
    ("Reference & configuration", "Docs: Agent config changes in CLI 3.0",
     "What changed in the agent format, and when to use Markdown versus JSON for a config.",
     "https://kiro.dev/docs/cli/v3/agent-config/", "Official docs"),
    ("Reference & configuration", "Docs: Billing reference",
     "Breakdown of service tiers and which features each one includes.",
     "https://kiro.dev/docs/billing/", "Official docs"),
    ("Reference & configuration", "Docs: Available models",
     "Per-model detail: capabilities, behavioural differences and lifecycle status.",
     "https://kiro.dev/docs/models/available-models/", "Official docs"),
    ("Reference & configuration", "Docs: Reasoning effort",
     "Tune how much reasoning a model applies to trade speed against depth and cost.",
     "https://kiro.dev/docs/models/effort/", "Official docs"),
    ("Reference & configuration", "Docs: Authentication",
     "All sign-in routes (GitHub, Google, Builder ID, IAM Identity Center) and how to generate a CLI API key.",
     "https://kiro.dev/docs/getting-started/authentication/", "Official docs"),
    ("Reference & configuration", "Kiro web portal (app.kiro.dev)",
     "Sign-in portal for the web app and account/usage pages. If it fails to load, suspect a firewall or proxy blocking required domains.",
     "https://app.kiro.dev/", "Official site"),

    # ---------------- Skills, checkpoints, compaction ----------------
    ("Skills, checkpoints & context", "Docs: Agent skills",
     "Reusable instruction packages that activate when your request matches their description, or explicitly via / slash commands.",
     "https://kiro.dev/docs/skills/", "Official docs"),
    ("Skills, checkpoints & context", "Docs: Checkpoints and rewind",
     "How Kiro snapshots files before the agent edits them so you can revert to any earlier point.",
     "https://kiro.dev/docs/checkpoints/", "Official docs"),
    ("Skills, checkpoints & context", "Docs: New features in CLI 3.0",
     "Dense summary of Plan mode (Shift+Tab), trusted workspaces, manual /compact, skills discovery, steering front matter, session export and sub-agents.",
     "https://kiro.dev/docs/cli/v3/new-features/", "Official docs"),
    ("Skills, checkpoints & context", "Docs: Hook examples",
     "Working hook implementations with trigger types and target patterns you can adapt directly.",
     "https://kiro.dev/docs/hooks/examples/", "Official docs"),
    ("Skills, checkpoints & context", "Docs: Hook triggers reference",
     "Detailed description of each trigger, its matcher behaviour and typical use cases.",
     "https://kiro.dev/docs/hooks/types/", "Official docs"),
    ("Skills, checkpoints & context", "Docs: Hook actions",
     "How command actions receive event data on STDIN, and how agent actions inject prompts.",
     "https://kiro.dev/docs/hooks/actions/", "Official docs"),
    ("Skills, checkpoints & context", "Docs: Multi-root workspaces",
     "Adding several folders to one Kiro window via File > Add Folder to Workspace, or by dragging them into the Explorer.",
     "https://kiro.dev/docs/ide/editor/multi-root-workspaces/", "Official docs"),
    ("Skills, checkpoints & context", "Blog: Multi-root workspaces",
     "The reasoning behind multi-root support and the cross-project workflows it unlocks.",
     "https://kiro.dev/blog/multi-root-workspaces/", "Official blog"),
    ("Skills, checkpoints & context", "Docs: Requirements-first spec workflow",
     "The classic spec route - settle what the system should do before deciding how to build it.",
     "https://kiro.dev/docs/specs/feature-specs/requirements-first/", "Official docs"),
    ("Skills, checkpoints & context", "Community skill: requirements engineering (EARS)",
     "Shared skill that turns vague ideas into testable EARS requirements, with edge cases and completeness checks.",
     "https://skillsmp.com/creators/jasonkneen/kiro/skills-requirements-engineering", "Community library"),

    # ---------------- CI/CD, headless, automation ----------------
    ("CI/CD, headless & automation", "Docs: Headless mode",
     "Run the CLI non-interactively in CI/CD with an API key to review code, generate tests or diagnose build failures.",
     "https://kiro.dev/docs/cli/headless/", "Official docs"),
    ("CI/CD, headless & automation", "Blog: Introducing headless mode",
     "Announcement with a worked GitHub Actions example, including storing KIRO_API_KEY as a repository secret.",
     "https://kiro.dev/blog/introducing-headless-mode/", "Official blog"),
    ("CI/CD, headless & automation", "Docs: API key governance",
     "Admin control over whether users may generate API keys at all.",
     "https://kiro.dev/docs/enterprise/governance/api-keys/", "Official docs"),
    ("CI/CD, headless & automation", "Changelog CLI 2.0: Windows support, headless mode, TUI",
     "Release notes for the flags that make headless runs work: --no-interactive, --trust-all-tools, --trust-tools.",
     "https://kiro.dev/changelog/cli/2-0/", "Official changelog"),
    ("CI/CD, headless & automation", "GitHub Action: run Kiro on PRs and issues",
     "Community action that runs Kiro from a comment mention, an issue label or an explicit workflow prompt, then opens a PR.",
     "https://github.com/karancode/kiro-action", "GitHub"),
    ("CI/CD, headless & automation", "GitHub Action: install and cache Kiro CLI",
     "Setup action for workflows, with headless IAM (SIGV4) authentication.",
     "https://github.com/clouatre-labs/setup-kiro-action", "GitHub"),
    ("CI/CD, headless & automation", "GitHub Action: automated PR review with Kiro CLI",
     "Review action that only reacts to @kiro comments from trusted roles, so stray events do not burn credits.",
     "https://github.com/konippi/kiro-cli-review-action", "GitHub"),
    ("CI/CD, headless & automation", "Marketplace listing: Kiro CLI Review Action",
     "The same review action on GitHub Marketplace, with its event-filtering behaviour described.",
     "https://github.com/marketplace/actions/kiro-cli-review-action", "Marketplace"),
    ("CI/CD, headless & automation", "Docker docs: Kiro in agent sandboxes",
     "Running Kiro inside Docker's agent sandboxes; notes that Kiro uses interactive device-flow sign-in rather than stored API keys.",
     "https://docs.docker.com/ai/sandboxes/agents/kiro/", "Vendor docs"),
    ("CI/CD, headless & automation", "Multi-agent workspace architecture for kiro-cli",
     "Community pattern for organising several agents, shared context, learned memory and task tracking in one workspace.",
     "https://github.com/wilbur-labs/kiro-workspace", "GitHub"),

    # ---------------- Powers & integrations ----------------
    ("Integrations & partners", "Kiro Powers directory",
     "Browse available powers - packaged best practices from tool vendors and domain experts for design, dev, deploy and observability.",
     "https://kiro.dev/powers/", "Official site"),
    ("Integrations & partners", "Blog: Introducing Kiro powers",
     "Why powers exist: load specialised tools and context on demand instead of overloading the agent up front.",
     "https://kiro.dev/blog/introducing-powers/", "Official blog"),
    ("Integrations & partners", "HashiCorp on being a Kiro powers launch partner",
     "Partner perspective on bundling MCP tools, steering files and hooks into a single installable power.",
     "https://www.hashicorp.com/en/blog/hashicorp-is-a-kiro-powers-launch-partner", "Vendor blog"),
    ("Integrations & partners", "Kiro has Terraform skills",
     "Walkthrough of the Terraform-focused skills and how they help with provider work.",
     "https://manuchandrasekhar.medium.com/kiro-has-terraform-skills-6819c43e8dfb", "Medium"),
    ("Integrations & partners", "Spec-driven IaC development with Kiro and Terraform",
     "Hands-on report of applying the spec workflow to infrastructure code.",
     "https://developer.mamezou-tech.com/en/blogs/2025/09/08/kiro-spec-terraform-iac/", "Community blog"),
    ("Integrations & partners", "Figma's guide to the Figma MCP server",
     "Official Figma documentation for the MCP server, including the catalog of supported clients.",
     "https://help.figma.com/hc/en-us/articles/32132100833559-Guide-to-the-Figma-MCP-server", "Vendor docs"),
    ("Integrations & partners", "Community MCP bridge between Kiro and Figma",
     "Community MCP server letting Kiro read and modify Figma designs programmatically.",
     "https://github.com/rosydaqbar/kiro-talk-to-figma-mcp", "GitHub"),
    ("Integrations & partners", "Issue #6441: Figma code-to-canvas tool support",
     "Tracking issue about write-side Figma tools; notes Kiro is listed as a supported client for the read-only tools.",
     "https://github.com/kirodotdev/Kiro/issues/6441", "GitHub issue"),
    ("Integrations & partners", "AWS blog: transform DevOps practice with Kiro agents",
     "Public-sector oriented look at applying Kiro agents to DevOps workflows.",
     "https://aws.amazon.com/blogs/publicsector/transform-devops-practice-with-kiro-ai-powered-agents/", "AWS blog"),
    ("Integrations & partners", "AWS startups prompt library: Kiro project init",
     "Ready-made prompt that scaffolds a spec-driven project with tests and AWS integrations in one command.",
     "https://aws.amazon.com/startups/prompt-library/kiro-project-init", "AWS resource"),
    ("Integrations & partners", "InfoQ: AWS open-sources Kiro Crew",
     "Independent news coverage of Crew - shared memory, reusable skills, scheduled jobs, concurrent agents and MCP/webhook integrations.",
     "https://www.infoq.com/news/2026/08/kiro-crew-coding-agents/", "News"),
    ("Integrations & partners", "GitHub: KiroCrew repository",
     "Source and bundled skills for Kiro Crew.",
     "https://github.com/kirodotdev/KiroCrew", "GitHub"),
    ("Integrations & partners", "Docs: Crew agent capabilities",
     "What an agent config controls in Crew: model, system prompt, callable tools and which MCP servers to spawn.",
     "https://kiro.dev/docs/crew/capabilities/agents/", "Official docs"),

    # ---------------- Networking / privacy operations ----------------
    ("Networking, privacy & ops", "Docs: Firewalls, proxies and data perimeters",
     "The definitive allowlist - every domain Kiro contacts, grouped by function. Start here for corporate network failures.",
     "https://kiro.dev/docs/privacy-and-security/firewalls/", "Official docs"),
    ("Networking, privacy & ops", "Docs: Data protection",
     "What is stored where, and the difference in treatment between enterprise profiles and individual accounts.",
     "https://kiro.dev/docs/privacy-and-security/data-protection/", "Official docs"),
    ("Networking, privacy & ops", "Docs: Prompt logging for admins",
     "Enabling logs of inline suggestions and chat conversations for audit, debugging, analytics and compliance.",
     "https://kiro.dev/docs/enterprise/monitor-and-track/prompt-logging/", "Official docs"),
    ("Networking, privacy & ops", "Docs: Per-user activity reports",
     "Daily CSV telemetry per subscriber for auditing usage, reallocating licences and tracking credit or overage consumption.",
     "https://kiro.dev/docs/enterprise/monitor-and-track/user-activity/", "Official docs"),
    ("Networking, privacy & ops", "Docs: Enterprise settings",
     "Admin-side toggles applied through the Kiro profile.",
     "https://kiro.dev/docs/enterprise/settings/", "Official docs"),
    ("Networking, privacy & ops", "Check your opt-out settings before using Kiro (Japanese)",
     "Walks through the service-improvement opt-out and why to check it on day one.",
     "https://zenn.dev/shirochan/articles/331d0ecac815ce", "Community blog"),
    ("Networking, privacy & ops", "What to know before starting: data privacy and security (Japanese)",
     "Corporate-blog summary of Kiro's data handling for teams doing a security review.",
     "https://blog.serverworks.co.jp/kiro-data-privacy-security", "Community blog"),
    ("Networking, privacy & ops", "Using MCP servers through a corporate proxy (Japanese)",
     "Concrete fix for uvx-based MCP servers failing behind a company proxy, using ~/.kiro/settings/mcp.json.",
     "https://kdnakt.hatenablog.com/entry/2025/12/19/kiro-uvx-mcp-servers-over-corporate-proxy", "Community blog"),
    ("Networking, privacy & ops", "Fixing 'Failed to connect to MCP server'",
     "Diagnoses the most common cause - the uv/uvx package manager is simply not installed.",
     "https://www.qes.co.jp/media/aws/Kiro/a822", "Community blog"),
    ("Networking, privacy & ops", "Issue #1850: MCP error",
     "Community thread collecting MCP connection failures and workarounds.",
     "https://github.com/kirodotdev/Kiro/issues/1850", "GitHub issue"),
    ("Networking, privacy & ops", "MCP discussion: 'spawn uvx ENOENT'",
     "Upstream explanation of the ENOENT error when the runtime for an MCP server is missing from PATH.",
     "https://github.com/orgs/modelcontextprotocol/discussions/20", "GitHub"),
    ("Networking, privacy & ops", "npm-based MCP servers failing while uvx ones work",
     "Upstream issue with the resolution in the comments - useful when only some of your servers connect.",
     "https://github.com/modelcontextprotocol/servers/issues/76", "GitHub issue"),

    # ---------------- Migration from Amazon Q ----------------
    ("Migration from Amazon Q", "Docs: Upgrading from Q CLI to Kiro CLI",
     "Official migration notes, including that auto-update moved Q Developer CLI to Kiro CLI and how to update manually if you had it disabled.",
     "https://kiro.dev/docs/upgrade-guides/migrating-from-q/", "Official docs"),
    ("Migration from Amazon Q", "AWS docs: upgrade to Kiro",
     "AWS-side guidance for admins and individuals; the Kiro console is a rebrand of the Amazon Q Developer console with the same functionality.",
     "https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/upgrade-to-kiro.html", "AWS docs"),
    ("Migration from Amazon Q", "Amazon Q to Kiro migration playbook",
     "Third-party playbook stressing this is not a rename: Visual Studio and Eclipse users have no native Kiro plugin, and specs/hooks/steering have no Q equivalent.",
     "https://www.digitalapplied.com/blog/amazon-q-to-kiro-migration-playbook", "Community blog"),
    ("Migration from Amazon Q", "Q Developer CLI setup and migration notes",
     "Community reference with the rebrand timeline and the end-of-support date for Amazon Q Developer IDE plugins.",
     "https://markaicode.com/howto/amazon-q-setup-and-configuration-guide/", "Community blog"),
    ("Migration from Amazon Q", "From Amazon Q Developer CLI to Kiro CLI (Japanese, AWS blog)",
     "AWS Japan's rundown of exactly what changed for CLI users in the transition.",
     "https://aws.amazon.com/jp/blogs/news/kiroweeeeeeek-in-japan-day-6-amazon-q-developer-cli-to-kiro-cli/", "AWS blog"),

    # ---------------- EARS / requirements craft ----------------
    ("Writing requirements (EARS)", "Writing effective requirements.md using EARS notation",
     "Practical guide to EARS in a Kiro requirements file, and how the fixed sentence shape exposes vague conditions.",
     "https://signiance.com/writing-effective-requirements-md-in-kiro-using-ears-notation/", "Community blog"),
    ("Writing requirements (EARS)", "EARS notation: a practical guide",
     "Requirements-engineering vendor guide to EARS, referencing Kiro's insistence on structured requirements before code.",
     "https://www.modernrequirements.com/es/blogs/ears-notation-the-practical-guide/", "Vendor blog"),
    ("Writing requirements (EARS)", "Spec process guide: standards and EARS keywords",
     "The keyword set that makes requirements clear, testable and unambiguous.",
     "https://github.com/jasonkneen/kiro/blob/main/spec-process-guide/resources/standards.md", "GitHub"),
    ("Writing requirements (EARS)", "Gist: Kiro spec workflow documentation and templates",
     "Copy-paste requirements template with the WHEN/IF ... THEN ... SHALL acceptance-criteria pattern.",
     "https://gist.github.com/prabhu-mannu/62ad499b690fcbe33c6f40ee5279aa69", "Gist / notes"),
    ("Writing requirements (EARS)", "9 PRD and spec templates built for AI coding agents",
     "Survey of spec/PRD templates designed to be read by an agent as primary context.",
     "https://ssojet.com/blog/prd-spec-templates-ai-agents", "Community blog"),

    # ---------------- Videos, courses, cheat sheets ----------------
    ("Videos, courses & cheat sheets", "Kiro CLI cheat sheet (PDF)",
     "One-page printable command and slash-command reference for the CLI.",
     "https://blog.brianbeach.com/posts/2026-01-19-kiro-cli-cheat-sheet/kiro-cli-cheat-sheet.pdf", "Cheat sheet (PDF)"),
    ("Videos, courses & cheat sheets", "Kiro CLI notes from a 10-video tutorial series",
     "Written distillation of a video course, so you can skim instead of watching hours of footage.",
     "https://github.com/chasko-labs/kiro-cli-notes", "GitHub"),
    ("Videos, courses & cheat sheets", "Udemy: AWS Kiro Masterclass - spec-driven agentic AI development",
     "Paid course building Requirements, Design and Task files from business requirements. Check reviews and recency before buying.",
     "https://www.udemy.com/course/aws-kiro-masterclass-spec-driven-agentic-ai-development/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Udemy: Kiro bootcamp - AI coding, automation and vibe coding",
     "Project-based paid course from front-end work up to multi-agent systems.",
     "https://www.udemy.com/course/kiro-bootcamp-ai-coding-automation-vibe-coding/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Udemy: spec-driven development with AI (Kiro and Spec Kit)",
     "Compares quick prototyping against spec-driven work and covers more than one SDD toolchain.",
     "https://www.udemy.com/course/spec-driven-development-with-ai/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Udemy: AWS Kiro - build AI applications and cloud workflows",
     "Course on orchestrating agent-based development from prototype to production, including terminal execution.",
     "https://www.udemy.com/course/aws-kiro-build-ai-applications-cloud-workflows/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Udemy: Amazon Kiro hands-on - build apps with AI agents",
     "Hands-on course positioning Kiro against general-purpose assistants.",
     "https://www.udemy.com/course/amazon-kiro-handson-build-apps-with-ai-agents-q-developer/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Udemy: SDD - designing deterministic AI systems",
     "Tool-agnostic course treating the spec as a contract with measurable criteria, using EARS-style templates.",
     "https://www.udemy.com/course/spec-driven-development-designing-deterministic-ai-systems/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Udemy: curso completo de Spec Driven Development (Spanish)",
     "Spanish-language SDD course covering Kiro alongside other agents and local models.",
     "https://www.udemy.com/course/curso-completo-de-spec-driven-development-sdd-y-agentes-ia/", "Course (paid)"),
    ("Videos, courses & cheat sheets", "Kiro for students",
     "Official student page with programme details and student-built project examples.",
     "https://kiro.dev/students/", "Official site"),

    # ---------------- Hackathons ----------------
    ("Hackathons & events", "Code with Kiro Hackathon (winners announced)",
     "The flagship Devpost hackathon. The gallery is a large, browsable set of real Kiro-built projects with write-ups.",
     "https://kiro.devpost.com/updates/37154-and-the-winner-is", "Hackathon"),
    ("Hackathons & events", "Blog: This is Kiroween",
     "Announcement of the annual Halloween-themed hackathon, with the prize structure.",
     "https://kiro.dev/blog/kiroween-2025/", "Official blog"),
    ("Hackathons & events", "Kiroween hackathon rules",
     "Devpost rules page - useful as a template for how these events are structured and judged.",
     "https://kiroween.devpost.com/rules", "Hackathon"),
    ("Hackathons & events", "Kiro Buildfest Singapore",
     "Regional event page describing the spec-first pitch for newcomers.",
     "https://sg-kiro-buildfest.devpost.com/", "Hackathon"),
    ("Hackathons & events", "Reddit and Kiro community games challenge",
     "Joint virtual hackathon for community games built with Kiro.",
     "https://communitygames2025.devpost.com/rules", "Hackathon"),
    ("Hackathons & events", "Quickstart template used for Kiro hackathons",
     "Project scaffold aimed at getting a hackathon entry moving quickly.",
     "https://github.com/0xkgt/starting-point", "GitHub"),

    # ---------------- Japanese / other language resources ----------------
    ("Non-English resources", "Qiita: all articles tagged Kiro (Japanese)",
     "Live feed of Japanese Kiro articles - one of the most active non-English communities for this tool.",
     "https://qiita.com/tags/kiro", "Community hub"),
    ("Non-English resources", "Zenn: all articles tagged Kiro (Japanese)",
     "The other major Japanese feed, sorted by all-time popularity.",
     "https://zenn.dev/topics/kiro?order=alltime", "Community hub"),
    ("Non-English resources", "Beginner's tour of Kiro and spec-driven development (Japanese)",
     "Clear re-introduction to what Kiro is and what spec-driven development actually means in practice.",
     "https://zenn.dev/beagle/articles/1dea6ff60b1143", "Community blog"),
    ("Non-English resources", "Recent state of Kiro since subscriptions launched (Japanese)",
     "Useful for understanding how the plans and limits landed with real users.",
     "https://zenn.dev/beagle/articles/5360946ada5607", "Community blog"),
    ("Non-English resources", "Detailed explainer of Kiro as an AI-driven dev tool (Japanese)",
     "Long-form breakdown centred on the Spec mode as the defining feature.",
     "https://zenn.dev/galirage/articles/aws-ai-native-kiro", "Community blog"),
    ("Non-English resources", "Spec-driven generation versus vibe coding, compared (Japanese)",
     "Side-by-side experiment generating requirements, design and plan from a single prompt.",
     "https://zenn.dev/pepabo/articles/c9458242a78876", "Community blog"),
    ("Non-English resources", "Design with Kiro, implement with Claude (Japanese)",
     "Report on a hybrid workflow splitting planning and implementation across two tools.",
     "https://zenn.dev/ueshiii/articles/f3902756a3958d", "Community blog"),
    ("Non-English resources", "Learning specs, hooks and steering by analogy (Japanese)",
     "Explains Kiro's primitives using a familiar IT-certification framing.",
     "https://zenn.dev/tkithrta/articles/e5e67fedb11436", "Community blog"),
    ("Non-English resources", "Trying spec-driven development in Kiro - beginner report (Japanese)",
     "Qiita walkthrough of a first spec from a self-described beginner.",
     "https://qiita.com/hirokiii27/items/d3d1ac5995ea08a40787", "Community blog"),
    ("Non-English resources", "Kiro CLI getting started (Japanese)",
     "Notes contrasting the project-bound IDE with the CLI you can run anywhere.",
     "https://github.com/rewse/zenn-content/blob/main/articles/kiro-cli-getting-started.md", "GitHub"),
    ("Non-English resources", "Kiro introduction: the three Kiros and when to use each (Japanese)",
     "Corporate column comparing the IDE, CLI and web surfaces with usage examples.",
     "https://biz.nuro.jp/column/aws-engineer-038/", "Community blog"),
    ("Non-English resources", "Sorting out when to use the IDE versus the CLI (Japanese)",
     "Engineering-blog take on choosing a surface for a given task.",
     "https://persol-serverworks.co.jp/blog/kiro/kiro.html", "Community blog"),
    ("Non-English resources", "Introducing Kiro (Japanese, AWS blog)",
     "The AWS Japan translation of the original launch announcement.",
     "https://aws.amazon.com/jp/blogs/news/introducing-kiro/", "AWS blog"),
    ("Non-English resources", "AWS docs: upgrade to Kiro (Spanish)",
     "Spanish version of the Amazon Q to Kiro upgrade guidance.",
     "https://docs.aws.amazon.com/es_es/amazonq/latest/qdeveloper-ug/upgrade-to-kiro.html", "AWS docs"),
    ("Non-English resources", "AWS docs: upgrade to Kiro (Portuguese)",
     "Portuguese version of the same upgrade guidance.",
     "https://docs.aws.amazon.com/pt_br/amazonq/latest/qdeveloper-ug/upgrade-to-kiro.html", "AWS docs"),
    ("Non-English resources", "Kiro docs in French",
     "The official documentation is localised; swap /docs/ for /fr/docs/ for French. Other locales follow the same pattern.",
     "https://kiro.dev/fr/docs/", "Official docs"),

    # ---------------- Real-world practice ----------------
    ("Real-world practice", "How we use Kiro at Lap 1 Labs",
     "Team retrospective on which patterns actually stuck: multi-root workspaces, steering discipline and more.",
     "https://medium.com/@dustin_44710/how-we-use-kiro-at-lap-1-labs-q2-update-26fa6c8cebf9", "Medium"),
    ("Real-world practice", "Personal Kiro CLI configuration with orchestrator and layered security",
     "A full real-world .kiro setup: multi-agent orchestration, per-language steering and a self-learning knowledge system.",
     "https://github.com/rommelporras/kiro-config", "GitHub"),
    ("Real-world practice", "Winning a hackathon with Kiro plus another agent (Japanese)",
     "Detailed account of shipping a working app in hours using spec-driven development under time pressure.",
     "https://zenn.dev/mashharuki/articles/web3_ai_vibecoding", "Community blog"),
    ("Real-world practice", "Docs: Learn by playing - environment setup",
     "The setup step for the sample-game tutorial, including connecting a local client and server.",
     "https://kiro.dev/docs/guides/learn-by-playing/00-setup/", "Official tutorial"),
    ("Real-world practice", "Kiro Documentation hub (AWS)",
     "AWS framing of Kiro as an agentic coding service that turns prompts into specs, then code, docs and tests.",
     "https://aws.amazon.com/documentation-overview/kiro/", "AWS docs"),
]



# ---------------------------------------------------------------------
# Safety net: drop any URL that appears more than once, keeping the first
# occurrence so each link is listed exactly once in the workbook.
# ---------------------------------------------------------------------
def _dedupe(rows):
    seen = set()
    out = []
    for row in rows:
        url = row[3]
        if url in seen:
            continue
        seen.add(url)
        out.append(row)
    return out


_BEFORE = len(ROWS)
ROWS = _dedupe(ROWS)
DUPES_REMOVED = _BEFORE - len(ROWS)
